import json
import shutil
import subprocess
import cairo
import caelestia_core
from src.lang import t
from gi.repository import Gtk, Adw, GLib
from src.hypr_provider import (
    ConfigCapability,
    Provider,
    ManagedBlockError,
    find_competing_lua_autostart_entries,
    find_lines_outside_managed_blocks,
    load_provider,
    read_managed_legacy_block,
    read_managed_lua_block,
    resolve_path,
    require_config_capability,
    write_managed_legacy_block_and_reload,
    write_managed_lua_block,
    write_managed_lua_block_and_reload,
)

MONITORS_LUA_BLOCK = "monitors"
MONITORS_CONF_BLOCK = "monitors"
MONITORS_LEGACY_MARKER = "# Auto-generated by Caelestia Settings – Monitore"
PRIMARY_MONITOR_BLOCK = "primary-monitor"
MONITOR_QUERY_TIMEOUT_SECONDS = 3


class MonitorDisableSafetyError(RuntimeError):
    """A monitor-disable request could not be proven to leave an active output."""

# ── Konstanten ────────────────────────────────────────────────────────────────

ROTATION_OPTIONS = [
    ("0",   t("Normal (0°)")),
    ("1",   t("90° right")),
    ("2",   "180°"),
    ("3",   t("270° right / 90° left")),
]

BITDEPTH_OPTIONS = [
    ("",   t("Standard (8 bit)")),
    ("8",  "8 bit"),
    ("10", t("10 bit (HDR)")),
]

# Farben für Monitor-Rechtecke (Index → RGBA)
MONITOR_COLORS = [
    (0.27, 0.52, 0.93, 1.0),   # Blau
    (0.20, 0.78, 0.56, 1.0),   # Grün
    (0.93, 0.47, 0.27, 1.0),   # Orange
    (0.73, 0.40, 0.93, 1.0),   # Lila
    (0.93, 0.27, 0.47, 1.0),   # Rot
]

CANVAS_H = 220   # Höhe der Vorschau-Canvas in Pixeln


# ── Hilfsfunktionen ───────────────────────────────────────────────────────────

def _query_hyprctl_monitors_all() -> list[dict]:
    """Return validated ``hyprctl -j monitors all`` output.

    Hyprland documents ``monitors all`` as including active and inactive
    outputs.  The strict boolean ``disabled`` field is therefore the
    authoritative live-state discriminator used by the disable guard.
    """
    try:
        res = subprocess.run(
            ["hyprctl", "-j", "monitors", "all"],
            capture_output=True,
            text=True,
            check=True,
            timeout=MONITOR_QUERY_TIMEOUT_SECONDS,
        )
        monitors = json.loads(res.stdout)
    except (OSError, subprocess.SubprocessError, json.JSONDecodeError) as error:
        raise MonitorDisableSafetyError(
            t("Could not determine active monitors; disabling was blocked.")
        ) from error

    if not isinstance(monitors, list):
        raise MonitorDisableSafetyError(
            t("Could not determine active monitors; disabling was blocked.")
        )

    names = set()
    for item in monitors:
        if not isinstance(item, dict):
            raise MonitorDisableSafetyError(
                t("Could not determine active monitors; disabling was blocked.")
            )
        name = item.get("name")
        disabled = item.get("disabled")
        if not isinstance(name, str) or not name.strip() or type(disabled) is not bool or name in names:
            raise MonitorDisableSafetyError(
                t("Could not determine active monitors; disabling was blocked.")
            )
        names.add(name)
    return monitors


def _live_monitor_name_sets() -> tuple[set[str], set[str]]:
    monitors = _query_hyprctl_monitors_all()
    known = {item["name"] for item in monitors}
    active = {item["name"] for item in monitors if item["disabled"] is False}
    return active, known


def _requested_disabled_monitor_names(monitors: list) -> set[str]:
    requested = set()
    seen = set()
    for item in monitors:
        name = item.get("name") if isinstance(item, dict) else getattr(item, "name", None)
        disabled = item.get("disabled") if isinstance(item, dict) else getattr(item, "disabled", None)
        if not isinstance(name, str) or not name.strip() or type(disabled) is not bool or name in seen:
            raise MonitorDisableSafetyError(
                t("Could not validate the requested monitor configuration; disabling was blocked.")
            )
        seen.add(name)
        if disabled:
            requested.add(name)
    return requested


def _ensure_safe_monitor_disable_names(
    requested_disabled: set[str], *, writer_provider: Provider | None = None
) -> None:
    require_config_capability(ConfigCapability.MONITORS, writer_provider=writer_provider)
    if not requested_disabled:
        return

    active, known = _live_monitor_name_sets()
    if not requested_disabled <= known:
        raise MonitorDisableSafetyError(
            t("Could not determine active monitors; disabling was blocked.")
        )

    actively_disabled = requested_disabled & active
    if not actively_disabled:
        return  # Every requested output is already disabled: a safe no-op.
    if not active - requested_disabled:
        raise MonitorDisableSafetyError(t("The last active monitor cannot be disabled."))


def _ensure_safe_monitor_disable(
    monitors: list, *, writer_provider: Provider | None = None
) -> None:
    _ensure_safe_monitor_disable_names(
        _requested_disabled_monitor_names(monitors), writer_provider=writer_provider
    )


def _verify_monitor_disable_applied(
    monitors: list, *, writer_provider: Provider | None = None
) -> None:
    require_config_capability(ConfigCapability.MONITORS, writer_provider=writer_provider)
    requested_disabled = _requested_disabled_monitor_names(monitors)
    if not requested_disabled:
        return
    active, known = _live_monitor_name_sets()
    if not requested_disabled <= known or requested_disabled & active or not active:
        raise MonitorDisableSafetyError(
            t("The monitor deactivation could not be verified; the change was rolled back.")
        )


def _get_live_monitors() -> list[dict]:
    """Liefert die aktuellen Monitor-Daten von hyprctl, angereichert mit
    Extras aus monitors.conf (bitdepth).

    Raises `MonitorDisableSafetyError` when the live state cannot be
    determined (deliberately NOT swallowed to an empty list here) — a
    genuinely empty result and an unreadable one are not the same thing,
    and `MonitorPage.load_monitors()` (the only real caller) must be able
    to tell them apart to show a neutral/unknown UI state instead of a
    confidently empty one."""
    provider = load_provider()
    if provider is None:
        return []
    monitors = _query_hyprctl_monitors_all()

    # Extras (bitdepth) aus der providereigenen Datei lesen — hyprctl liefert
    # den aktuellen Live-Zustand unabhängig vom Provider, aber bitdepth ist
    # kein Feld in dessen JSON-Ausgabe.
    extras = _parse_monitors_lua_extras() if provider is Provider.LUA else _parse_conf_extras()
    for m in monitors:
        name = m.get("name", "")
        if name in extras:
            m.update(extras[name])
    return monitors


def _parse_conf_extras() -> dict:
    """
    Liest monitors.conf und extrahiert pro Monitor-Name:
    { "DP-1": {"bitdepth": "10"}, "DP-2": {"bitdepth": ""} }
    """
    from src.config import HYPR_MONITORS_CONF
    result = {}
    if not HYPR_MONITORS_CONF.exists():
        return result
    try:
        for line in HYPR_MONITORS_CONF.read_text().splitlines():
            line = line.strip()
            if not line.startswith("monitor"):
                continue
            rest = line.split("=", 1)[1]
            # Komma-getrennte Tokens, Extras nach Index 3
            tokens = [t.strip() for t in rest.split(",")]
            if len(tokens) < 1:
                continue
            name = tokens[0]
            extras = {"bitdepth": ""}
            # Suche nach "bitdepth" Token
            for i, tok in enumerate(tokens):
                if tok.lower() == "bitdepth" and i + 1 < len(tokens):
                    extras["bitdepth"] = tokens[i + 1].strip()
            result[name] = extras
    except Exception as e:
        print(f"Fehler beim Lesen von monitors.conf extras: {e}")
    return result


# ── Lua provider ──────────────────────────────────────────────────────────
#
# monitors.lua holds two independent app-managed blocks in the same file:
# "monitors" (hl.monitor(...) calls, written here) and "workspaces"
# (hl.workspace_rule(...) calls, written by workspaces.py). Each block is
# only ever touched by its own owner via write_managed_lua_block(), so the
# two pages never clobber each other's entries.
#
# TODO(hyprland-lua-migration): monitors.lua must actually be loaded by the
# user's hyprland.lua (e.g. via a require/dofile line) for any of this to
# take effect — wiring that up during install is M8's job, not this page's.


def _parse_monitors_lua_extras() -> dict:
    """Mirrors _parse_conf_extras() but reads bitdepth back out of the
    app-managed hl.monitor(...) block in monitors.lua instead of .conf."""
    path = resolve_path("monitors", Provider.LUA)
    result = {}
    for line in read_managed_lua_block(path, MONITORS_LUA_BLOCK):
        line = line.strip()
        if not line.startswith("hl.monitor("):
            continue
        try:
            _, args = caelestia_core.parse_lua_call(line)
        except ValueError:
            continue
        if not args or not isinstance(args[0], dict):
            continue
        table = args[0]
        name = table.get("output", "")
        if not name:
            continue
        bitdepth = table.get("bitdepth", "")
        result[name] = {"bitdepth": str(bitdepth) if bitdepth else ""}
    return result


def _build_monitor_lua_table(m) -> dict:
    """Builds the hl.monitor({...}) argument table for one monitor,
    matching Hyprland's own example syntax (output/mode/position/scale,
    optional bitdepth/transform; disabled monitors use mode = "disable",
    mirroring the .conf provider's `,disable` field)."""
    if m.disabled:
        return {"output": m.name, "mode": "disable"}

    table = {
        "output": m.name,
        "mode": f"{m.resolution}@{m.hz}" if m.hz else m.resolution,
        "position": f"{int(m.x)}x{int(m.y)}",
        "scale": round(float(m.scale), 4),
    }
    if m.bitdepth:
        table["bitdepth"] = int(m.bitdepth)
    if m.transform and m.transform != "0":
        table["transform"] = int(m.transform)
    return table


def _save_monitors_lua(monitors: list) -> None:
    """Renders every monitor as an hl.monitor({...}) call and safely
    replaces the "monitors" managed block in monitors.lua. Raises
    LuaWriteError (propagated from write_managed_lua_block) if the
    generated file fails luac validation — the file on disk is then left
    unchanged."""
    require_config_capability(ConfigCapability.MONITORS, writer_provider=Provider.LUA)
    _ensure_safe_monitor_disable(monitors, writer_provider=Provider.LUA)
    path = resolve_path("monitors", Provider.LUA)
    lines = [caelestia_core.render_lua_call("hl.monitor", [_build_monitor_lua_table(m)]) for m in monitors]
    write_managed_lua_block(
        path,
        MONITORS_LUA_BLOCK,
        lines,
        pre_write_check=lambda _text: _ensure_safe_monitor_disable(
            monitors, writer_provider=Provider.LUA
        ),
    )


def _save_monitors_lua_and_reload(monitors: list) -> None:
    require_config_capability(ConfigCapability.MONITORS, writer_provider=Provider.LUA)
    _ensure_safe_monitor_disable(monitors, writer_provider=Provider.LUA)
    path = resolve_path("monitors", Provider.LUA)
    lines = [caelestia_core.render_lua_call("hl.monitor", [_build_monitor_lua_table(m)]) for m in monitors]
    write_managed_lua_block_and_reload(
        path,
        MONITORS_LUA_BLOCK,
        lines,
        pre_write_check=lambda _text: _ensure_safe_monitor_disable(
            monitors, writer_provider=Provider.LUA
        ),
        verify=lambda: _verify_monitor_disable_applied(
            monitors, writer_provider=Provider.LUA
        ),
    )


def _apply_to_hyprland(monitors: list[dict]):
    """Schickt alle Monitor-Konfigurationen live an Hyprland."""
    require_config_capability(ConfigCapability.MONITORS, writer_provider=Provider.HYPRLANG)
    _ensure_safe_monitor_disable(monitors, writer_provider=Provider.HYPRLANG)
    for m in monitors:
        keyword = _build_monitor_keyword(m)
        try:
            subprocess.run(
                ["hyprctl", "keyword", "monitor", keyword],
                check=True, timeout=3
            )
        except Exception as e:
            raise RuntimeError(f"hyprctl keyword monitor: {e}") from e
    _verify_monitor_disable_applied(monitors, writer_provider=Provider.HYPRLANG)


def _save_monitors_conf(monitors: list):
    """Replace only the app-owned monitor block in monitors.conf."""
    require_config_capability(ConfigCapability.MONITORS, writer_provider=Provider.HYPRLANG)
    _ensure_safe_monitor_disable(monitors, writer_provider=Provider.HYPRLANG)
    from src.config import HYPR_MONITORS_CONF
    lines = [f"monitor = {_build_monitor_keyword(m)}" for m in monitors]
    write_managed_legacy_block_and_reload(
        HYPR_MONITORS_CONF,
        MONITORS_CONF_BLOCK,
        lines,
        legacy_marker=MONITORS_LEGACY_MARKER,
        pre_write_check=lambda _text: _ensure_safe_monitor_disable(
            monitors, writer_provider=Provider.HYPRLANG
        ),
        verify=lambda: _verify_monitor_disable_applied(
            monitors, writer_provider=Provider.HYPRLANG
        ),
    )


# ── execs.conf / execs.lua Helpers ───────────────────────────────────────────
#
# execs.lua is shared with wallpaper.py's video-autostart entry (see
# src/pages/wallpaper.py), but each page only ever touches its own named
# managed block — "primary-monitor" here, "wallpaper-autostart" there —
# so updating or clearing one can never affect the other, any manually
# written exec content, or a manual xrandr/exec directive that merely
# looks similar (never treated as app-owned just because of matching
# content, only because it sits inside this app's own named block).


def _get_primary_monitor(provider: Provider | None = None) -> str:
    """Liest den aktuellen app-eigenen Hauptmonitor-Eintrag aus dem
    "primary-monitor" managed block in execs.conf/execs.lua. Returns ""
    both when no primary is set AND when the true effective state is
    undetermined because a competing foreign handler exists — callers
    that need to distinguish those two cases (i.e. the UI) must also
    check `_has_competing_primary_monitor_handler()`."""
    if provider is None:
        provider = load_provider()
    if provider is None:
        return ""
    path = resolve_path("execs", provider)
    if provider is Provider.LUA:
        lines = read_managed_lua_block(path, PRIMARY_MONITOR_BLOCK)
        for line in lines:
            try:
                cmd = caelestia_core.parse_autostart_cmd(line)
                return caelestia_core.parse_xrandr_primary_cmd(cmd)
            except ValueError:
                continue
        return ""

    lines = read_managed_legacy_block(path, PRIMARY_MONITOR_BLOCK)
    for line in lines:
        line = line.strip()
        if not line.startswith("exec-once"):
            continue
        cmd = line.split("=", 1)[1].strip() if "=" in line else ""
        try:
            return caelestia_core.parse_xrandr_primary_cmd(cmd)
        except ValueError:
            continue
    return ""


def _competing_primary_monitor_lines(text: str, provider: Provider) -> list[str]:
    """Foreign (non-app-owned) content elsewhere in execs that plausibly
    also controls the primary monitor — see
    `find_competing_lua_autostart_entries`/`find_lines_outside_managed_blocks`
    in hypr_provider.py for the detection semantics."""

    def relevant(cmd: str) -> bool:
        return "xrandr" in cmd and "--primary" in cmd

    if provider is Provider.LUA:
        return find_competing_lua_autostart_entries(text, [PRIMARY_MONITOR_BLOCK], relevant)
    return [
        line
        for line in find_lines_outside_managed_blocks(text, [PRIMARY_MONITOR_BLOCK], "#")
        if line.strip().startswith("exec-once") and relevant(line)
    ]


def _has_competing_primary_monitor_handler(provider: Provider | None = None) -> bool:
    """True when some entry OUTSIDE the app's own "primary-monitor" block
    could also be setting/clearing the X11 primary output — Hyprland runs
    every autostart entry it finds, not just this app's own, so such an
    entry means the true effective primary monitor cannot be reliably
    read back from this app's own persisted value alone."""
    if provider is None:
        provider = load_provider()
    if provider is None:
        return False
    path = resolve_path("execs", provider)
    if not path.exists():
        return False
    text = path.read_bytes().decode("utf-8")
    return bool(_competing_primary_monitor_lines(text, provider))


def _raise_if_competing_primary_monitor(text: str, provider: Provider) -> None:
    if _competing_primary_monitor_lines(text, provider):
        raise ManagedBlockError(
            t(
                "Another manually written primary-monitor exec entry exists outside the "
                "app-managed block; resolve the conflict manually before saving."
            )
        )


def _write_primary_monitor_lines(
    provider: Provider,
    lines: list[str],
    *,
    pre_write_check=None,
    live_apply=None,
) -> None:
    path = resolve_path("execs", provider)
    if provider is Provider.LUA:
        write_managed_lua_block_and_reload(
            path, PRIMARY_MONITOR_BLOCK, lines, pre_write_check=pre_write_check, live_apply=live_apply
        )
    else:
        write_managed_legacy_block_and_reload(
            path, PRIMARY_MONITOR_BLOCK, lines, pre_write_check=pre_write_check, live_apply=live_apply
        )


def _apply_primary_monitor_live(name: str | None) -> None:
    """Applies the primary-monitor change live via a direct `xrandr` call
    — this is an X11/XWayland-level concept, not part of Hyprland's own
    compositor config. `--noprimary` (a real, documented xrandr flag,
    distinct from the per-output `--primary` flag) clears the primary
    designation entirely — see `man xrandr`, "Don't define a primary
    output." Crucially, `hyprctl reload` never re-triggers the
    `hyprland.start` event an autostart entry is registered against, so
    persisting the execs entry alone would only take effect at the next
    Hyprland/X11 session start — this direct call is the ONLY way to
    change the currently running session's primary output immediately.

    Raises `RuntimeError` — never prints and swallows — on a non-zero
    exit code, a timeout, a missing `xrandr` binary, or any other failure
    to run it, with the returncode/stderr preserved in the message. Does
    NOT additionally verify the change via a `--listmonitors`-style
    read-back: xrandr's primary-output flag reporting is not reliably
    consistent when running against an XWayland server (the normal case
    for this app, a Hyprland/Wayland settings tool), and a false-negative
    verification would cause a spurious rollback of an otherwise-
    successful change, which is worse than not verifying at all.
    """
    xrandr = shutil.which("xrandr")
    if xrandr is None:
        raise RuntimeError(t("xrandr was not found; the primary monitor change was not applied live."))
    args = [xrandr, "--output", name, "--primary"] if name else [xrandr, "--noprimary"]
    try:
        result = subprocess.run(args, capture_output=True, text=True, timeout=3)
    except subprocess.TimeoutExpired as e:
        raise RuntimeError(f"xrandr timed out: {e}") from e
    except OSError as e:
        raise RuntimeError(f"xrandr failed to run: {e}") from e
    if result.returncode != 0:
        raise RuntimeError((result.stderr or "").strip() or f"xrandr exited with code {result.returncode}")


def _set_primary_monitor(name: str | None):
    """Persists (or clears, when `name` is None) the app-owned primary
    monitor exec entry for the currently active provider under the
    "primary-monitor" managed block, THEN applies it live via `xrandr` —
    with the live-apply call running INSIDE the writer's own lock/
    transaction (see `live_apply` on `write_managed_lua_block_and_reload`/
    `write_managed_legacy_block_and_reload`), not as a separate step
    afterwards. This is what makes the rollback base correct even under
    concurrency: if the live-apply fails, the writer rolls back to
    exactly the bytes THIS transaction read as its starting point under
    the same lock — never a snapshot taken before the lock was acquired,
    which could already be stale if another writer's change was
    serialized in between. Fails closed (no write, no live action) if
    another manually written entry outside the app-managed block also
    plausibly controls the primary monitor."""
    provider = require_config_capability(ConfigCapability.EXECS)

    if name:
        cmd = caelestia_core.render_xrandr_primary_cmd(name)
        lines = (
            [caelestia_core.render_autostart_cmd(cmd)]
            if provider is Provider.LUA
            else [f"exec-once = {cmd}"]
        )
    else:
        lines = []

    def pre_write_check(text: str) -> None:
        _raise_if_competing_primary_monitor(text, provider)

    def live_apply() -> None:
        _apply_primary_monitor_live(name)

    _write_primary_monitor_lines(
        provider, lines, pre_write_check=pre_write_check, live_apply=live_apply
    )


# ── shell.json Helpers ───────────────────────────────────────────────────────

def _get_bar_persistent(monitor_name: str) -> bool:
    """Liest ob die Taskleiste für diesen Monitor persistent ist."""
    import json
    from pathlib import Path
    shell = Path.home() / ".config/caelestia/monitors" / monitor_name / "shell.json"
    if not shell.exists():
        return True  # Standard: Taskleiste an
    try:
        data = json.loads(shell.read_text())
        return data.get("bar", {}).get("persistent", True)
    except Exception as e:
        print(f"shell.json lesen fehler: {e}")
        return True


def _set_bar_persistent(monitor_name: str, persistent: bool):
    """Schreibt den persistent-Wert in shell.json."""
    import json
    from pathlib import Path
    shell_dir = Path.home() / ".config/caelestia/monitors" / monitor_name
    shell_dir.mkdir(parents=True, exist_ok=True)
    shell = shell_dir / "shell.json"
    try:
        data = {}
        if shell.exists():
            data = json.loads(shell.read_text())
        data.setdefault("bar", {})["persistent"] = persistent
        shell.write_text(json.dumps(data, indent=4))
    except Exception as e:
        print(f"shell.json schreiben fehler: {e}")


def _build_monitor_keyword(m) -> str:
    """
    Baut den Hyprland monitor-Keyword-String aus einem MonitorModel.
    DP-1,2560x1440@179.95,0x0,1,bitdepth,10,transform,3
    """
    if m.disabled:
        return f"{m.name},disable"

    res_hz = f"{m.resolution}@{m.hz}" if m.hz else m.resolution
    pos    = f"{int(m.x)}x{int(m.y)}"
    parts  = [m.name, res_hz, pos, str(m.scale)]

    if m.bitdepth:
        parts += ["bitdepth", m.bitdepth]

    if m.transform and m.transform != "0":
        parts += ["transform", m.transform]

    return ",".join(parts)


def _parse_mode(mode_str: str) -> tuple[str, str]:
    """'2560x1440@179.950Hz' → ('2560x1440', '179.950')"""
    if "@" in mode_str:
        res, hz = mode_str.split("@", 1)
        hz = hz.replace("Hz", "").strip()
        try:
            hz = f"{float(hz):.3f}"   # normalisieren auf 3 Dezimalstellen
        except ValueError:
            pass
        return res, hz
    return mode_str, ""


# ── Monitor-Datenmodell ───────────────────────────────────────────────────────

class MonitorModel:
    """Hält den Zustand eines Monitors (editierbar)."""

    def __init__(self, data: dict):
        self.name        = data["name"]
        self.description = data.get("description", self.name)
        self.x           = float(data.get("x", 0))
        self.y           = float(data.get("y", 0))
        self.width       = int(data.get("width", 1920))
        self.height      = int(data.get("height", 1080))
        self.scale       = float(data.get("scale", 1.0))
        self.transform   = str(int(data.get("transform", 0)))
        self.disabled    = data.get("disabled", False)

        # Aktive Auflösung + Hz
        self.resolution  = f"{self.width}x{self.height}"
        self.hz          = f"{round(data.get('refreshRate', 60), 3):.3f}"

        # Bitdepth aus monitors.conf (via _parse_conf_extras angereichert)
        self.bitdepth    = str(data.get("bitdepth", ""))
        # Hauptmonitor-Flag — wird separat aus execs.conf gesetzt
        self.primary     = False
        # True wenn ein konkurrierender, nicht app-eigener Handler den
        # Hauptmonitor ebenfalls setzen könnte — der effektive Zustand ist
        # dann unbestimmt, .primary bleibt in diesem Fall immer False
        self.primary_conflict = False
        # Taskleiste persistent — wird aus shell.json geladen
        self.bar_persistent = True

        # Alle Modi
        self.available_modes: list[str] = data.get("availableModes", [])
        if not self.available_modes:
            self.available_modes = [f"{self.resolution}@{self.hz}Hz"]

        # Deduplizierte Auflösungen + Hz-Optionen pro Auflösung
        self._res_map: dict[str, list[str]] = {}
        for mode in self.available_modes:
            r, h = _parse_mode(mode)
            self._res_map.setdefault(r, []).append(h)

    @property
    def logical_w(self) -> float:
        """Logische Breite. hyprctl liefert bereits getauschte width/height
        bei rotierten Monitoren, also immer width/scale."""
        return self.width / self.scale

    @property
    def logical_h(self) -> float:
        return self.height / self.scale

    def resolutions(self) -> list[str]:
        return sorted(self._res_map.keys(),
                      key=lambda r: int(r.split("x")[0]), reverse=True)

    def hz_for_resolution(self, res: str) -> list[str]:
        return sorted(self._res_map.get(res, []),
                      key=lambda h: float(h) if h else 0, reverse=True)

    def to_save_dict(self) -> dict:
        return {
            "name":       self.name,
            "resolution": self.resolution,
            "hz":         self.hz,
            "x":          self.x,
            "y":          self.y,
            "scale":      self.scale,
            "transform":  self.transform,
            "bitdepth":   self.bitdepth,
        }


# ── Canvas ────────────────────────────────────────────────────────────────────

class MonitorCanvas(Gtk.DrawingArea):
    """
    Zeichnet alle Monitore als Rechtecke.
    Klick → Monitor auswählen.
    Drag → Monitor verschieben (snap an anderen Monitoren).
    """

    def __init__(self, on_select_cb):
        super().__init__()
        self.on_select_cb = on_select_cb
        self.monitors: list[MonitorModel] = []
        self.selected: MonitorModel | None = None
        self._drag_mon: MonitorModel | None = None
        self._drag_off_x = 0.0
        self._drag_off_y = 0.0

        self.set_vexpand(False)
        self.set_hexpand(True)
        self.set_content_height(CANVAS_H)
        self.set_draw_func(self._draw)

        # Gesten
        click = Gtk.GestureClick()
        click.connect("pressed", self._on_press)
        self.add_controller(click)

        drag = Gtk.GestureDrag()
        drag.connect("drag-begin",  self._on_drag_begin)
        drag.connect("drag-update", self._on_drag_update)
        drag.connect("drag-end",    self._on_drag_end)
        self.add_controller(drag)

    # ── Koordinaten-Umrechnung ────────────────────────────────────────────

    def _canvas_rect(self, m: MonitorModel, scale: float, ox: float, oy: float):
        """Gibt (cx, cy, cw, ch) in Canvas-Pixeln zurück."""
        cw = max(m.logical_w * scale, 40)
        ch = max(m.logical_h * scale, 30)
        cx = ox + m.x * scale
        cy = oy + m.y * scale
        return cx, cy, cw, ch

    def _view_scale_offset(self) -> tuple[float, float, float]:
        """Berechnet Skalierungsfaktor und Offset so dass alle Monitore passen."""
        if not self.monitors:
            return 0.1, 20, 20

        active = [m for m in self.monitors if not m.disabled]
        if not active:
            return 0.1, 20, 20

        min_x = min(m.x for m in active)
        min_y = min(m.y for m in active)
        max_x = max(m.x + m.logical_w for m in active)
        max_y = max(m.y + m.logical_h for m in active)

        w = self.get_width()
        h = self.get_height()
        pad = 32

        sw = (w - 2 * pad) / max(max_x - min_x, 1)
        sh = (h - 2 * pad) / max(max_y - min_y, 1)
        s  = min(sw, sh, 0.18)   # max 0.18 px/logical-px

        ox = pad - min_x * s + (w - 2*pad - (max_x-min_x)*s) / 2
        oy = pad - min_y * s + (h - 2*pad - (max_y-min_y)*s) / 2
        return s, ox, oy

    # ── Zeichnen ──────────────────────────────────────────────────────────

    def _draw(self, area, cr, w, h):
        s, ox, oy = self._view_scale_offset()

        # Hintergrund
        cr.set_source_rgba(0.12, 0.12, 0.12, 1)
        cr.rectangle(0, 0, w, h)
        cr.fill()

        # Gitter
        cr.set_source_rgba(1, 1, 1, 0.04)
        cr.set_line_width(1)
        step = 40
        for gx in range(0, w, step):
            cr.move_to(gx, 0); cr.line_to(gx, h)
        for gy in range(0, h, step):
            cr.move_to(0, gy); cr.line_to(w, gy)
        cr.stroke()

        for i, m in enumerate(self.monitors):
            if m.disabled:
                continue
            cx, cy, cw, ch = self._canvas_rect(m, s, ox, oy)
            r, g, b, a = MONITOR_COLORS[i % len(MONITOR_COLORS)]
            selected = (m is self.selected)

            # Schatten
            cr.set_source_rgba(0, 0, 0, 0.4)
            cr.rectangle(cx + 4, cy + 4, cw, ch)
            cr.fill()

            # Füllung
            alpha = 1.0 if selected else 0.75
            cr.set_source_rgba(r * 0.6, g * 0.6, b * 0.6, alpha)
            cr.rectangle(cx, cy, cw, ch)
            cr.fill()

            # Rahmen
            lw = 3 if selected else 1.5
            cr.set_line_width(lw)
            cr.set_source_rgba(r, g, b, 1.0)
            cr.rectangle(cx, cy, cw, ch)
            cr.stroke()

            # Name
            cr.set_source_rgba(1, 1, 1, 0.95)
            cr.select_font_face("Sans", cairo.FONT_SLANT_NORMAL,
                                cairo.FONT_WEIGHT_BOLD if selected else cairo.FONT_WEIGHT_NORMAL)
            font_size = max(min(cw / 6, 16), 9)
            cr.set_font_size(font_size)
            ext = cr.text_extents(m.name)
            cr.move_to(cx + cw/2 - ext.width/2, cy + ch/2 - 2)
            cr.show_text(m.name)

            # Auflösung
            res_str = f"{m.resolution}@{float(m.hz):.0f}Hz"
            cr.set_font_size(max(font_size * 0.7, 7))
            cr.set_source_rgba(1, 1, 1, 0.7)
            ext2 = cr.text_extents(res_str)
            if ext2.width < cw - 8:
                cr.move_to(cx + cw/2 - ext2.width/2, cy + ch/2 + font_size)
                cr.show_text(res_str)

            # Rotation-Indikator
            if m.transform != "0":
                deg = {"1": "90°", "2": "180°", "3": "270°"}.get(m.transform, "")
                cr.set_font_size(max(font_size * 0.65, 7))
                cr.set_source_rgba(1, 1, 0.4, 0.9)
                cr.move_to(cx + 4, cy + 14)
                cr.show_text(f"↻ {deg}")

    # ── Interaktion ───────────────────────────────────────────────────────

    def _mon_at(self, px, py) -> MonitorModel | None:
        s, ox, oy = self._view_scale_offset()
        for m in reversed(self.monitors):
            if m.disabled: continue
            cx, cy, cw, ch = self._canvas_rect(m, s, ox, oy)
            if cx <= px <= cx+cw and cy <= py <= cy+ch:
                return m
        return None

    def _on_press(self, gesture, n, px, py):
        m = self._mon_at(px, py)
        self.selected = m
        self.queue_draw()
        self.on_select_cb(m)

    def _on_drag_begin(self, gesture, sx, sy):
        self._drag_mon = self._mon_at(sx, sy)
        if self._drag_mon:
            s, ox, oy = self._view_scale_offset()
            self._drag_off_x = (sx - ox) / s - self._drag_mon.x
            self._drag_off_y = (sy - oy) / s - self._drag_mon.y

    def _on_drag_update(self, gesture, dx, dy):
        if not self._drag_mon: return
        sx, sy = gesture.get_start_point()[1], gesture.get_start_point()[2]
        px, py = sx + dx, sy + dy
        s, ox, oy = self._view_scale_offset()
        new_x = (px - ox) / s - self._drag_off_x
        new_y = (py - oy) / s - self._drag_off_y
        self._drag_mon.x = round(new_x)
        self._drag_mon.y = round(new_y)
        self.queue_draw()

    def _on_drag_end(self, gesture, dx, dy):
        if self._drag_mon:
            self._snap(self._drag_mon)
            self.queue_draw()
        self._drag_mon = None

    def _snap(self, m: MonitorModel, threshold: float = 30):
        """Rastet Monitor an benachbarten Monitoren ein."""
        for other in self.monitors:
            if other is m or other.disabled:
                continue
            # Horizontal
            for mx in [m.x, m.x + m.logical_w]:
                for ox_ in [other.x, other.x + other.logical_w]:
                    if abs(mx - ox_) < threshold:
                        m.x += ox_ - mx
            # Vertikal
            for my in [m.y, m.y + m.logical_h]:
                for oy_ in [other.y, other.y + other.logical_h]:
                    if abs(my - oy_) < threshold:
                        m.y += oy_ - my


# ── Einstellungs-Panel ────────────────────────────────────────────────────────

class MonitorSettingsPanel(Gtk.Box):
    """Zeigt Einstellungen für den ausgewählten Monitor."""

    def __init__(self):
        super().__init__(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self._monitor: MonitorModel | None = None
        self._loading = False
        self._on_primary_exclusive_cb = None
        self._on_disable_error_cb = None
        self._can_disable_hint_cb = None

        self._placeholder = Adw.StatusPage()
        self._placeholder.set_icon_name("video-display-symbolic")
        self._placeholder.set_title(t("No monitor selected"))
        self._placeholder.set_description(t("Click on a monitor in the preview."))
        self._placeholder.set_vexpand(True)
        self.append(self._placeholder)

        self._panel = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self._panel.set_vexpand(True)
        self._panel.set_visible(False)
        self.append(self._panel)

        scroller = Gtk.ScrolledWindow()
        scroller.set_vexpand(True)
        scroller.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        self._panel.append(scroller)

        self._group = Adw.PreferencesGroup()
        self._group.set_margin_top(8)
        self._group.set_margin_bottom(12)
        self._group.set_margin_start(12)
        self._group.set_margin_end(12)
        scroller.set_child(self._group)

        # ── Auflösung ──
        res_row = Adw.ActionRow(title=t("Resolution"))
        self._res_combo = Gtk.ComboBoxText()
        self._res_combo.set_valign(Gtk.Align.CENTER)
        self._res_combo.connect("changed", self._on_res_changed)
        res_row.add_suffix(self._res_combo)
        self._group.add(res_row)

        # ── Bildwiederholrate ──
        hz_row = Adw.ActionRow(title=t("Refresh rate"))
        self._hz_combo = Gtk.ComboBoxText()
        self._hz_combo.set_valign(Gtk.Align.CENTER)
        self._hz_combo.connect("changed", self._on_hz_changed)
        hz_row.add_suffix(self._hz_combo)
        self._group.add(hz_row)

        # ── Drehung ──
        rot_row = Adw.ActionRow(title=t("Rotation"))
        self._rot_combo = Gtk.ComboBoxText()
        self._rot_combo.set_valign(Gtk.Align.CENTER)
        for r_id, r_lbl in ROTATION_OPTIONS:
            self._rot_combo.append(r_id, r_lbl)
        self._rot_combo.connect("changed", self._on_rot_changed)
        rot_row.add_suffix(self._rot_combo)
        self._group.add(rot_row)

        # ── Farbtiefe ──
        bd_row = Adw.ActionRow(title=t("Bit depth"))
        self._bd_combo = Gtk.ComboBoxText()
        self._bd_combo.set_valign(Gtk.Align.CENTER)
        for b_id, b_lbl in BITDEPTH_OPTIONS:
            self._bd_combo.append(b_id, b_lbl)
        self._bd_combo.connect("changed", self._on_bd_changed)
        bd_row.add_suffix(self._bd_combo)
        self._group.add(bd_row)

        # ── Skalierung ──
        scale_row = Adw.ActionRow(title=t("Scale"))
        self._scale_spin = Gtk.SpinButton.new_with_range(0.25, 4.0, 0.25)
        self._scale_spin.set_digits(2)
        self._scale_spin.set_valign(Gtk.Align.CENTER)
        self._scale_spin.connect("value-changed", self._on_scale_changed)
        scale_row.add_suffix(self._scale_spin)
        self._group.add(scale_row)

        # ── Aktiviert ──
        self._enabled_row = Adw.SwitchRow(title=t("Monitor enabled"))
        self._enabled_row.connect("notify::active", self._on_enabled_changed)
        self._group.add(self._enabled_row)

        # ── Hauptmonitor ──
        self._primary_row = Adw.SwitchRow(
            title=t("Primary monitor"),
            subtitle=t("xrandr --primary (for X11 apps and tray)")
        )
        self._primary_row.connect("notify::active", self._on_primary_changed)
        self._group.add(self._primary_row)

        # ── Taskleiste ──
        self._bar_row = Adw.SwitchRow(
            title=t("Always show taskbar"),
            subtitle="shell.json: bar.persistent"
        )
        self._bar_row.connect("notify::active", self._on_bar_changed)
        self._group.add(self._bar_row)

    def load(self, m: MonitorModel | None):
        self._monitor = m
        self._loading = True

        if m is None:
            self._placeholder.set_visible(True)
            self._panel.set_visible(False)
            self._loading = False
            return

        self._placeholder.set_visible(False)
        self._panel.set_visible(True)
        self._group.set_title(f"{m.name}  –  {m.description}")

        # Auflösungen laden
        self._res_combo.remove_all()
        for r in m.resolutions():
            self._res_combo.append(r, r)
        self._res_combo.set_active_id(m.resolution)

        # Hz laden — normalisiere auf 3 Nachkommastellen für konsistenten Vergleich
        self._reload_hz(m.resolution)
        hz_norm = f"{float(m.hz):.3f}" if m.hz else ""
        if not self._hz_combo.set_active_id(hz_norm):
            # Fallback: ersten Eintrag nehmen
            self._hz_combo.set_active(0)
            first = self._hz_combo.get_active_id()
            if first:
                m.hz = first

        self._rot_combo.set_active_id(m.transform)
        self._bd_combo.set_active_id(m.bitdepth if m.bitdepth else "")
        self._scale_spin.set_value(m.scale)
        self._enabled_row.set_active(not m.disabled)
        can_disable = m.disabled or self._can_disable_hint_cb is None
        if not can_disable:
            can_disable = bool(self._can_disable_hint_cb(m))
        self._enabled_row.set_sensitive(can_disable)
        self._enabled_row.set_subtitle(
            "" if can_disable else t("The last active monitor cannot be disabled.")
        )
        self._primary_row.set_active(m.primary)
        if m.primary_conflict:
            # A competing, non-app-owned handler could also set the
            # primary monitor — the true effective state is undetermined,
            # so this must never confidently claim m.primary either way
            # (already forced False by load_monitors()); disable the
            # switch entirely rather than risk showing a wrong state.
            self._primary_row.set_sensitive(False)
            self._primary_row.set_subtitle(
                t("Overridden by another manual autostart entry — effective state undetermined")
            )
        else:
            primary_available = load_provider() is not None
            self._primary_row.set_sensitive(primary_available)
            self._primary_row.set_subtitle(t("xrandr --primary (for X11 apps and tray)"))
        self._bar_row.set_active(m.bar_persistent)

        self._loading = False

    def _reload_hz(self, resolution: str):
        self._hz_combo.remove_all()
        if not self._monitor: return
        for h in self._monitor.hz_for_resolution(resolution):
            # ID immer als 3-Dezimalstellen-String für konsistenten Vergleich
            h_norm = f"{float(h):.3f}"
            self._hz_combo.append(h_norm, f"{float(h):.2f} Hz")

    def _on_res_changed(self, combo):
        if self._loading or not self._monitor: return
        res = combo.get_active_id()
        if not res: return
        self._monitor.resolution = res
        w, h = res.split("x")
        self._monitor.width  = int(w)
        self._monitor.height = int(h)
        self._loading = True
        self._reload_hz(res)
        # Höchste Hz als Default
        hz_list = self._monitor.hz_for_resolution(res)
        if hz_list:
            self._hz_combo.set_active_id(hz_list[0])
            self._monitor.hz = hz_list[0]
        self._loading = False

    def _on_hz_changed(self, combo):
        if self._loading or not self._monitor: return
        hz = combo.get_active_id()
        if hz: self._monitor.hz = hz

    def _on_rot_changed(self, combo):
        if self._loading or not self._monitor: return
        t = combo.get_active_id()
        if t is not None: self._monitor.transform = t

    def _on_bd_changed(self, combo):
        if self._loading or not self._monitor: return
        bd = combo.get_active_id()
        if bd is not None: self._monitor.bitdepth = bd

    def _on_scale_changed(self, spin):
        if self._loading or not self._monitor: return
        self._monitor.scale = spin.get_value()

    def _on_enabled_changed(self, row, _):
        if self._loading or not self._monitor: return
        wants_enabled = row.get_active()
        if not wants_enabled and not self._monitor.disabled:
            try:
                _ensure_safe_monitor_disable_names({self._monitor.name})
            except RuntimeError as error:
                self._loading = True
                try:
                    row.set_active(True)
                finally:
                    self._loading = False
                row.set_sensitive(False)
                row.set_subtitle(str(error))
                if self._on_disable_error_cb is not None:
                    self._on_disable_error_cb(str(error))
                return
        self._monitor.disabled = not row.get_active()
        row.set_sensitive(True)
        row.set_subtitle("")

    def _on_bar_changed(self, row, _):
        if self._loading or not self._monitor: return
        self._monitor.bar_persistent = row.get_active()

    def _on_primary_changed(self, row, _):
        if self._loading or not self._monitor: return
        self._monitor.primary = row.get_active()
        # Nur einer kann primär sein → alle anderen auf False
        if row.get_active():
            # Signal wird von MonitorPage via callback propagiert
            if hasattr(self, "_on_primary_exclusive_cb") and self._on_primary_exclusive_cb:
                self._on_primary_exclusive_cb(self._monitor)


# ── Haupt-Seite ───────────────────────────────────────────────────────────────

class MonitorPage(Gtk.Box):
    def __init__(self, main_window, **kwargs):
        super().__init__(**kwargs)
        self.main_window = main_window
        self.set_orientation(Gtk.Orientation.VERTICAL)
        self.set_spacing(0)
        self._monitors: list[MonitorModel] = []

        # ── Canvas ──
        canvas_frame = Gtk.Frame()
        canvas_frame.set_margin_top(12)
        canvas_frame.set_margin_start(12)
        canvas_frame.set_margin_end(12)
        self._canvas = MonitorCanvas(self._on_monitor_selected)
        canvas_frame.set_child(self._canvas)
        self.append(canvas_frame)

        # Canvas-Hinweis
        hint = Gtk.Label(label=t("Click to select  •  Drag to move"))
        hint.add_css_class("caption")
        hint.set_margin_top(4)
        hint.set_margin_bottom(8)
        self.append(hint)

        # ── Trennlinie ──
        self.append(Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL))

        # ── Einstellungs-Panel ──
        self._settings_panel = MonitorSettingsPanel()
        self._settings_panel._on_primary_exclusive_cb = self._on_primary_exclusive
        self._settings_panel._on_disable_error_cb = self._show_monitor_disable_error
        self._settings_panel._can_disable_hint_cb = self._can_disable_monitor_hint
        self.append(self._settings_panel)

        # ── Buttons ──
        btn_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        btn_box.set_halign(Gtk.Align.END)
        btn_box.set_margin_top(8)
        btn_box.set_margin_bottom(12)
        btn_box.set_margin_end(12)

        self._reload_btn = Gtk.Button(label=t("Reload"))
        self._reload_btn.connect("clicked", lambda _: self.load_monitors())
        btn_box.append(self._reload_btn)

        self._apply_btn = Gtk.Button(label=t("Apply"))
        self._apply_btn.add_css_class("suggested-action")
        self._apply_btn.connect("clicked", self._on_apply)
        btn_box.append(self._apply_btn)

        self.append(btn_box)

        self.load_monitors()

    def load_monitors(self):
        """Reloads the model and every widget from confirmed live state.

        This is the single source of truth for a "safe" UI state and is
        deliberately reused for three cases: the page's own initial load,
        the user-triggered Reload button, and — critically — recovery
        after a failed Apply (see `_on_apply`), where it is what turns a
        stale, never-actually-applied in-memory model/widget state back
        into one that matches reality. If the live state itself cannot
        be determined (e.g. `hyprctl` unreachable), this shows a neutral,
        fully disabled state instead of guessing — never a confidently
        empty or stale one."""
        if load_provider() is None:
            self._set_neutral_monitor_state()
            return

        try:
            raw = _get_live_monitors()
        except MonitorDisableSafetyError as error:
            self._set_neutral_monitor_state(error_message=str(error))
            return

        self._apply_btn.set_sensitive(True)
        self._canvas.set_sensitive(True)
        self._settings_panel.set_sensitive(True)

        self._monitors = [MonitorModel(m) for m in raw]

        # Hauptmonitor aus execs.conf/execs.lua markieren — bei einem
        # konkurrierenden fremden Handler bleibt der Zustand für jeden
        # Monitor unbestimmt (primary=False, primary_conflict=True),
        # statt fälschlich den eigenen persistierten Wert als effektiv
        # auszugeben.
        primary_conflict = _has_competing_primary_monitor_handler()
        primary_name = "" if primary_conflict else _get_primary_monitor()
        for m in self._monitors:
            m.primary = (not primary_conflict) and (m.name == primary_name)
            m.primary_conflict = primary_conflict
            m.bar_persistent = _get_bar_persistent(m.name)

        self._canvas.monitors = self._monitors
        self._canvas.selected = None
        self._canvas.queue_draw()
        self._settings_panel.load(None)

    def _set_neutral_monitor_state(self, *, error_message: str | None = None) -> None:
        """Shows the same disabled/empty placeholder state used when no
        provider is chosen yet, optionally with a visible error hint —
        used both for "no provider" and for "live state unreadable"
        (never a guessed value in either case). Widget updates here never
        trigger `MonitorSettingsPanel`'s own change handlers: `.load(None)`
        only shows the placeholder StatusPage, it never touches any of
        the input widgets those handlers are attached to."""
        self._apply_btn.set_sensitive(False)
        self._canvas.set_sensitive(False)
        self._settings_panel.set_sensitive(False)
        self._monitors = []
        self._canvas.monitors = []
        self._canvas.selected = None
        self._canvas.queue_draw()
        self._settings_panel.load(None)
        if error_message is not None:
            self.main_window.add_toast(Adw.Toast.new(error_message))

    def _on_monitor_selected(self, m: MonitorModel | None):
        self._settings_panel.load(m)
        self._canvas.queue_draw()

    def _on_primary_exclusive(self, primary_mon: MonitorModel):
        """Stellt sicher dass nur ein Monitor als primär markiert ist."""
        for m in self._monitors:
            if m is not primary_mon:
                m.primary = False

    def _can_disable_monitor_hint(self, monitor: MonitorModel) -> bool:
        return monitor.disabled or sum(not item.disabled for item in self._monitors) >= 2

    def _show_monitor_disable_error(self, message: str) -> None:
        self.main_window.add_toast(Adw.Toast.new(message))

    def _on_apply(self, _btn):
        provider = load_provider()
        if provider is None:
            self.main_window.add_toast(Adw.Toast.new(t("Choose a Hyprland configuration provider first.")))
            return
        try:
            if provider is Provider.LUA:
                # Write first, then reload — under Lua there is no per-field
                # `hyprctl keyword` (it fails outright, see issue #51), so
                # the only live-apply path is reloading the validated file.
                _save_monitors_lua_and_reload(self._monitors)
            else:
                _save_monitors_conf(self._monitors)

            # Hauptmonitor speichern (oder entfernen, wenn keiner markiert ist)
            primary_name = next((m.name for m in self._monitors if m.primary), None)
            _set_primary_monitor(primary_name)
        except Exception as e:
            # By the time we get here, the writer's own transaction —
            # including any internal rollback-and-reload — has already
            # fully completed (see write_managed_lua_block_and_reload's
            # `live_apply`/`_rollback_and_reload`). self._monitors and
            # every settings-panel widget may still hold values the user
            # picked but that were never actually applied (or were rolled
            # back), so they must never be left showing that stale,
            # unconfirmed state — reload from confirmed live state
            # instead of just returning after the error toast. No
            # success toast follows a failure, and no exception is
            # allowed to escape this GTK callback.
            self.main_window.add_toast(Adw.Toast.new(str(e)))
            GLib.timeout_add(600, self._reload_after_apply_failure)
            return

        # Taskleiste speichern
        for m in self._monitors:
            _set_bar_persistent(m.name, m.bar_persistent)
        GLib.timeout_add(600, self.load_monitors)
        self.main_window.add_toast(
            Adw.Toast.new(t("Monitor configuration saved and applied."))
        )

    def _reload_after_apply_failure(self) -> None:
        """Reloads model/UI from confirmed safe state after a failed
        Apply. Never lets an exception escape the GTK main loop: if the
        safety reload itself fails unexpectedly, falls back to the same
        neutral/disabled state `load_monitors` already uses for an
        unreadable live state, rather than leaving stale or guessed
        values on screen."""
        try:
            self.load_monitors()
        except Exception:
            self._set_neutral_monitor_state()

    def on_provider_changed(self):
        self.load_monitors()

    # Kompatibilität mit window.py (apply_btn dort entfernen wir später)
    def get_all_widget_settings(self):
        return {}
