import os
import subprocess
import threading
from pathlib import Path
from src.lang import t
from gi.repository import Gtk, Adw, GLib
from src.config import (
    load_window_rules_config, save_window_rules_config,
    parse_monitors_conf, parse_rules_conf,
    HYPR_RULES_CONF,
)

FLOAT_OPTIONS = [
    ("default", t("Standard (no rule)")),
    ("true",    "Float"),
    ("false",   t("No float")),
]

MATCH_TYPE_OPTIONS = [
    ("class",         "class"),
    ("initial_title", "initial_title"),
]

DESKTOP_DIRS = [
    Path("/usr/share/applications"),
    Path(os.path.expanduser("~/.local/share/applications")),
]

# ── .desktop-Parser ──────────────────────────────────────────────────────────

def _parse_desktop_file(path: Path) -> dict | None:
    data = {}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            in_section = False
            for line in f:
                line = line.strip()
                if line == "[Desktop Entry]":
                    in_section = True; continue
                if line.startswith("[") and line != "[Desktop Entry]":
                    in_section = False; continue
                if not in_section or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                key = key.strip(); value = value.strip()
                if "[" not in key:
                    data[key] = value
    except Exception as e:
        print(f"Fehler beim Parsen von {path}: {e}")
        return None

    if data.get("Type") != "Application":               return None
    if data.get("NoDisplay", "false").lower() == "true": return None
    if data.get("Hidden",    "false").lower() == "true": return None

    name     = data.get("Name", path.stem)
    icon     = data.get("Icon", "application-x-executable")
    wm_class = data.get("StartupWMClass", "")
    if not wm_class:
        exec_val = data.get("Exec", "")
        exec_bin = exec_val.split()[0] if exec_val else ""
        exec_bin = exec_bin.replace("%u","").replace("%U","").replace("%f","").replace("%F","").strip()
        wm_class = Path(exec_bin).name if exec_bin else ""

    is_web_app = "--app=" in data.get("Exec", "")
    return {"name": name, "icon": icon, "wm_class": wm_class,
            "is_web_app": is_web_app, "desktop_file": str(path)}


def _scan_desktop_files() -> list[dict]:
    apps = {}
    for directory in DESKTOP_DIRS:
        if not directory.exists(): continue
        for f in directory.glob("*.desktop"):
            info = _parse_desktop_file(f)
            if info and info["name"] not in apps:
                apps[info["name"]] = info
    return sorted(apps.values(), key=lambda a: a["name"].lower())


# ── rules.conf-Generator ─────────────────────────────────────────────────────

MANAGED_MARKER = "# Auto-generated by Caelestia Settings – Fenster-Regeln"

def _generate_rules_lines(rules: dict) -> list[str]:
    lines = [MANAGED_MARKER, ""]
    for key, settings in rules.items():
        if not key: continue
        workspace  = settings.get("workspace",  "default")
        float_val  = settings.get("float",      "default")
        match_type = settings.get("match_type", "class")
        match_str  = f"match:{match_type} {key}"
        if workspace != "default":
            lines.append(f"windowrule = workspace {workspace}, {match_str}")
        if float_val != "default":
            lines.append(f"windowrule = float {float_val}, {match_str}")
    return lines


def _write_rules_conf(new_lines: list[str]):
    HYPR_RULES_CONF.parent.mkdir(parents=True, exist_ok=True)
    existing_prefix = ""
    if HYPR_RULES_CONF.exists():
        raw = HYPR_RULES_CONF.read_text()
        if MANAGED_MARKER in raw:
            existing_prefix = raw.split(MANAGED_MARKER)[0].rstrip()
        else:
            existing_prefix = raw.rstrip()
    with open(HYPR_RULES_CONF, "w") as f:
        if existing_prefix:
            f.write(existing_prefix + "\n\n")
        f.write("\n".join(new_lines) + "\n")


# ── Haupt-Seite ──────────────────────────────────────────────────────────────

class WindowRulesPage(Gtk.Box):
    def __init__(self, main_window, **kwargs):
        super().__init__(**kwargs)
        self.main_window = main_window
        self.set_orientation(Gtk.Orientation.VERTICAL)

        # Workspace-Optionen dynamisch aus monitors.conf
        mon_data = parse_monitors_conf()
        self._workspace_options: list[tuple[str, str]] = mon_data["workspace_options"]

        # Lade gespeichertes JSON als Basis (diese werden beim Speichern geschrieben)
        self.saved_rules = load_window_rules_config()

        # Bestehende rules.conf einlesen
        self._existing_rules = parse_rules_conf()

        # Aus rules.conf gelesene Regeln NUR für Dropdown-Vorauswahl nutzen —
        # _imported_keys merkt sich welche Klassen NUR aus der rules.conf kommen,
        # damit sie beim Speichern NICHT nochmal geschrieben werden.
        self._imported_keys: set[str] = set()
        for entry in self._existing_rules:
            mv = entry["match_val"]
            if not mv:
                continue
            for cls in mv.split("|"):
                cls = cls.strip().lstrip("^(").rstrip(")$")
                if cls and cls not in self.saved_rules:
                    rule = entry["rule"].strip()
                    ws_rule    = ""
                    float_rule = "default"
                    if rule.startswith("workspace "):
                        ws_rule = rule.split("workspace ", 1)[1].strip()
                    elif rule.startswith("float "):
                        float_rule = rule.split("float ", 1)[1].strip()
                    if ws_rule or float_rule != "default":
                        self.saved_rules[cls] = {
                            "match_type": entry.get("match_type", "class"),
                            "workspace":  ws_rule or "default",
                            "float":      float_rule,
                        }
                        self._imported_keys.add(cls)
        self._rows: dict[str, "AppRuleRow"] = {}
        self._conflicts: list[str] = []

        # Notebook mit zwei Tabs
        notebook = Gtk.Notebook()
        notebook.set_vexpand(True)
        self.append(notebook)
        notebook.append_page(self._build_app_tab(),      Gtk.Label(label=t("App rules")))
        notebook.append_page(self._build_existing_tab(), Gtk.Label(label=t("Existing rules")))

    # ── Tab 1 ─────────────────────────────────────────────────────────────────

    def _build_app_tab(self) -> Gtk.Widget:
        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)

        # Toolbar
        bar = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        bar.set_margin_top(12); bar.set_margin_bottom(8)
        bar.set_margin_start(12); bar.set_margin_end(12)
        self.search_entry = Gtk.SearchEntry()
        self.search_entry.set_hexpand(True)
        self.search_entry.set_placeholder_text(t("Search app..."))
        self.search_entry.connect("search-changed", self._on_search_changed)
        bar.append(self.search_entry)
        save_btn = Gtk.Button(label=t("Save & Apply"))
        save_btn.add_css_class("suggested-action")
        save_btn.connect("clicked", self._on_save_clicked)
        bar.append(save_btn)
        box.append(bar)

        # Konflikt-Banner
        self.conflict_banner = Adw.Banner()
        self.conflict_banner.set_title(t("Conflicts detected"))
        self.conflict_banner.set_button_label(t("Details"))
        self.conflict_banner.connect("button-clicked", self._show_conflict_dialog)
        self.conflict_banner.set_revealed(False)
        box.append(self.conflict_banner)

        # Scroll + Liste
        scroller = Gtk.ScrolledWindow()
        scroller.set_vexpand(True)
        scroller.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        self.pref_group = Adw.PreferencesGroup()
        self.pref_group.set_margin_top(4); self.pref_group.set_margin_bottom(12)
        self.pref_group.set_margin_start(12); self.pref_group.set_margin_end(12)
        scroller.set_child(self.pref_group)
        box.append(scroller)

        self.spinner = Gtk.Spinner()
        self.spinner.set_halign(Gtk.Align.CENTER)
        self.spinner.set_size_request(-1, 48)
        box.append(self.spinner)
        self.spinner.start()
        threading.Thread(target=lambda: GLib.idle_add(
            self._populate_list, _scan_desktop_files()
        ), daemon=True).start()
        return box

    def _populate_list(self, apps: list[dict]):
        self.spinner.stop()
        self.spinner.set_visible(False)
        for app in apps:
            saved = self.saved_rules.get(app["wm_class"], {})
            row = AppRuleRow(app, saved, self._workspace_options, self._on_rule_changed)
            self._rows[app["name"]] = row
            self.pref_group.add(row)

    def _on_search_changed(self, entry):
        q = entry.get_text().lower()
        for name, row in self._rows.items():
            row.set_visible(q in name.lower())

    def _on_rule_changed(self):
        # Konflikterkennung: selbe wm_class → zwei verschiedene Workspaces
        seen: dict[str, str] = {}
        conflicts = []
        for row in self._rows.values():
            wm, s = row.get_rule()
            ws = s.get("workspace", "default")
            if ws == "default" or not wm: continue
            if wm in seen and seen[wm] != ws:
                conflicts.append(f"• {wm}: {seen[wm]} ↔ {ws}")
            seen[wm] = ws
        self._conflicts = conflicts
        if conflicts:
            self.conflict_banner.set_title(f"{len(conflicts)} {t('conflicts detected')}")
            self.conflict_banner.set_revealed(True)
        else:
            self.conflict_banner.set_revealed(False)

    def _show_conflict_dialog(self, *_):
        dialog = Adw.MessageDialog(heading="Konflikte", body="\n".join(self._conflicts) or "–")
        dialog.add_response("ok", "OK")
        dialog.set_transient_for(self.main_window)
        dialog.present()

    def _on_save_clicked(self, btn):
        if self._conflicts:
            self._show_conflict_dialog()
            return

        # Button während des Speicherns deaktivieren → verhindert Doppelklick
        btn.set_sensitive(False)
        btn.set_label(t("Saving..."))

        # Welche wm_classes haben bereits manuelle (nicht-managed) Regeln?
        manual_classes: set[str] = set()
        for entry in self._existing_rules:
            if not entry["managed"]:
                for cls in entry["match_val"].split("|"):
                    cls = cls.strip().lstrip("^(").rstrip(")$")
                    if cls:
                        manual_classes.add(cls)

        rules = {}
        for row in self._rows.values():
            key, settings = row.get_rule()
            ws     = settings.get("workspace", "default")
            float_ = settings.get("float",     "default")
            if ws == "default" and float_ == "default":
                continue
            # Klassen mit manueller Regel nur schreiben wenn User sie geändert hat
            if key in manual_classes and not row.is_user_modified():
                continue
            rules[key] = settings

        save_window_rules_config(rules)
        try:
            _write_rules_conf(_generate_rules_lines(rules))
            subprocess.run(["hyprctl", "reload"], timeout=3)
            self.main_window.add_toast(Adw.Toast.new(t("Rules saved and Hyprland reloaded.")))
            self._existing_rules = parse_rules_conf()
            self._refresh_existing_tab()
        except Exception as e:
            self.main_window.add_toast(Adw.Toast.new(f"Fehler: {e}"))
        finally:
            btn.set_sensitive(True)
            btn.set_label(t("Save & Apply"))

    # ── Tab 2 ─────────────────────────────────────────────────────────────────

    def _build_existing_tab(self) -> Gtk.Widget:
        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        lbl = Gtk.Label()
        lbl.set_markup(
            "<small>All <b>windowrule</b> entries from <tt>rules.conf</tt>  "
            "–  🔒 manual  /  ⚙ managed by this app</small>"
        )
        lbl.set_margin_top(10); lbl.set_margin_bottom(6); lbl.set_margin_start(12)
        lbl.set_halign(Gtk.Align.START)
        box.append(lbl)

        scroller = Gtk.ScrolledWindow()
        scroller.set_vexpand(True)
        scroller.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        self._existing_group = Adw.PreferencesGroup()
        self._existing_group.set_margin_top(4); self._existing_group.set_margin_bottom(12)
        self._existing_group.set_margin_start(12); self._existing_group.set_margin_end(12)
        scroller.set_child(self._existing_group)
        box.append(scroller)
        self._refresh_existing_tab()
        return box

    def _refresh_existing_tab(self):
        # AdwPreferencesGroup erlaubt kein remove() auf seine Rows —
        # stattdessen die Group komplett ersetzen.
        parent = self._existing_group.get_parent()   # ScrolledWindow
        new_group = Adw.PreferencesGroup()
        new_group.set_margin_top(4); new_group.set_margin_bottom(12)
        new_group.set_margin_start(12); new_group.set_margin_end(12)

        if not self._existing_rules:
            new_group.add(Adw.ActionRow(
                title="Keine windowrule-Einträge gefunden.",
                subtitle=str(HYPR_RULES_CONF)
            ))
        else:
            for entry in self._existing_rules:
                icon = "⚙" if entry["managed"] else "🔒"
                row  = Adw.ActionRow()
                row.set_title(f"{icon}  {entry['rule']}")
                row.set_subtitle(
                    f"match:{entry['match_type']} {entry['match_val']}"
                    if entry["match_type"] else entry["raw"]
                )
                new_group.add(row)

        if parent:
            parent.set_child(new_group)
        self._existing_group = new_group


# ── Einzelne App-Zeile ────────────────────────────────────────────────────────

class AppRuleRow(Adw.ActionRow):
    def __init__(self, app_info: dict, saved_settings: dict,
                 workspace_options: list[tuple[str, str]], on_change_cb):
        super().__init__()
        self._wm_class    = app_info["wm_class"]
        self._is_web_app  = app_info.get("is_web_app", False)
        self._cb          = on_change_cb


        self.set_title(app_info["name"])
        sub = app_info["wm_class"] or t("Unknown class")
        if self._is_web_app: sub += "  •  Web app"
        self.set_subtitle(sub)

        # Icon
        icon = Gtk.Image(); icon.set_pixel_size(32)
        icon_name = app_info.get("icon", "")
        theme = Gtk.IconTheme.get_for_display(icon.get_display()) if icon.get_display() else None
        if theme and icon_name and theme.has_icon(icon_name):
            icon.set_from_icon_name(icon_name)
        else:
            icon.set_from_icon_name("application-x-executable")
        icon.set_margin_end(8)
        self.add_prefix(icon)

        def _make_suffix(label_text, combo_options, saved_key, default_val):
            vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
            vbox.set_valign(Gtk.Align.CENTER)
            lbl = Gtk.Label(label=label_text)
            lbl.add_css_class("caption"); lbl.set_halign(Gtk.Align.START)
            vbox.append(lbl)
            combo = Gtk.ComboBoxText()
            for opt_id, opt_lbl in combo_options:
                combo.append(opt_id, opt_lbl)
            combo.set_active_id(saved_settings.get(saved_key, default_val))
            combo.connect("changed", lambda _: self._cb())
            vbox.append(combo)
            self.add_suffix(vbox)
            return combo

        default_match = "initial_title" if self._is_web_app else "class"
        self.match_combo = _make_suffix("Match",     MATCH_TYPE_OPTIONS, "match_type", default_match)
        self.ws_combo    = _make_suffix("Workspace", workspace_options,  "workspace",  "default")
        self.float_combo = _make_suffix(t("Behavior"), FLOAT_OPTIONS,      "float",      "default")

        # Ausgangszustand merken — zum Vergleich beim Speichern
        self._initial_state = {
            "match_type": self.match_combo.get_active_id() or "class",
            "workspace":  self.ws_combo.get_active_id()    or "default",
            "float":      self.float_combo.get_active_id() or "default",
        }

    def is_user_modified(self) -> bool:
        """True wenn der User mindestens einen Wert geändert hat."""
        current = {
            "match_type": self.match_combo.get_active_id() or "class",
            "workspace":  self.ws_combo.get_active_id()    or "default",
            "float":      self.float_combo.get_active_id() or "default",
        }
        return current != self._initial_state

    def get_rule(self) -> tuple[str, dict]:
        return self._wm_class, {
            "match_type": self.match_combo.get_active_id() or "class",
            "workspace":  self.ws_combo.get_active_id()    or "default",
            "float":      self.float_combo.get_active_id() or "default",
        }