import os
import threading
from pathlib import Path
from src.lang import t
from gi.repository import Gtk, Adw, GLib
from src.config import (
    load_window_rules_config, save_window_rules_config,
    build_workspace_options, parse_monitors_conf, parse_rules_conf,
    _fallback_ws_options, HYPR_RULES_CONF,
)
from src.hypr_provider import (
    Provider,
    load_provider,
    managed_block_byte_range,
    resolve_path,
    write_managed_legacy_block_and_reload,
    write_managed_lua_block,
    write_managed_lua_block_and_reload,
)
from src.pages.workspaces import _load_workspaces as _load_workspaces_shared

import caelestia_core

WINDOW_RULES_LUA_BLOCK = "window-rules"

FLOAT_OPTIONS = [
    ("default", t("Standard (no rule)")),
    ("true",    "Float"),
    ("false",   t("No float")),
]

MATCH_TYPE_OPTIONS = [
    ("class",         "class"),
    ("initial_title", "initial_title"),
]

DESKTOP_DIRS = [
    Path("/usr/share/applications"),
    Path(os.path.expanduser("~/.local/share/applications")),
]

# ── .desktop-Parser ──────────────────────────────────────────────────────────

def _parse_desktop_file(path: Path) -> dict | None:
    data = {}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            in_section = False
            for line in f:
                line = line.strip()
                if line == "[Desktop Entry]":
                    in_section = True; continue
                if line.startswith("[") and line != "[Desktop Entry]":
                    in_section = False; continue
                if not in_section or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                key = key.strip(); value = value.strip()
                if "[" not in key:
                    data[key] = value
    except Exception as e:
        print(f"Fehler beim Parsen von {path}: {e}")
        return None

    if data.get("Type") != "Application":               return None
    if data.get("NoDisplay", "false").lower() == "true": return None
    if data.get("Hidden",    "false").lower() == "true": return None

    name     = data.get("Name", path.stem)
    icon     = data.get("Icon", "application-x-executable")
    wm_class = data.get("StartupWMClass", "")
    if not wm_class:
        exec_val = data.get("Exec", "")
        exec_bin = exec_val.split()[0] if exec_val else ""
        exec_bin = exec_bin.replace("%u","").replace("%U","").replace("%f","").replace("%F","").strip()
        wm_class = Path(exec_bin).name if exec_bin else ""

    is_web_app = "--app=" in data.get("Exec", "")
    return {"name": name, "icon": icon, "wm_class": wm_class,
            "is_web_app": is_web_app, "desktop_file": str(path)}


def _scan_desktop_files() -> list[dict]:
    apps = {}
    for directory in DESKTOP_DIRS:
        if not directory.exists(): continue
        for f in directory.glob("*.desktop"):
            info = _parse_desktop_file(f)
            if info and info["name"] not in apps:
                apps[info["name"]] = info
    return sorted(apps.values(), key=lambda a: a["name"].lower())


# ── rules.conf-Generator ─────────────────────────────────────────────────────

MANAGED_MARKER = "# Auto-generated by Caelestia Settings – Fenster-Regeln"
RULES_CONF_BLOCK = "window-rules"

def _generate_rules_lines(rules: dict) -> list[str]:
    lines = []
    for key, settings in rules.items():
        if not key: continue
        workspace  = settings.get("workspace",  "default")
        float_val  = settings.get("float",      "default")
        match_type = settings.get("match_type", "class")
        match_str  = f"match:{match_type} {key}"
        if workspace != "default":
            lines.append(f"windowrule = workspace {workspace}, {match_str}")
        if float_val != "default":
            lines.append(f"windowrule = float {float_val}, {match_str}")
    return lines


def _write_rules_conf(new_lines: list[str]):
    write_managed_legacy_block_and_reload(
        HYPR_RULES_CONF,
        RULES_CONF_BLOCK,
        new_lines,
        legacy_marker=MANAGED_MARKER,
        legacy_line_predicate=lambda line: not line.strip() or line.strip().startswith("windowrule ="),
    )


# ── Lua provider ──────────────────────────────────────────────────────────
#
# rules.lua holds the app's own rules as hl.window_rule({...}) calls inside
# the "window-rules" managed block, and may additionally contain manual,
# hand-written hl.window_rule(...) calls anywhere else in the file — single-
# or multi-line, mixed in with comments, loops, dynamic values
# (vars.windowOpacity), other hl.* calls, and whatever else the user's Lua
# config does. Reading therefore never assumes one call per line outside the
# managed block: every hl.window_rule(...) in the whole file is located with
# caelestia_core.find_lua_calls (a boundary scanner, not a full Lua parser —
# see rust/caelestia-core/src/lua.rs), and each match is parsed
# independently. A match that isn't a supported static shape (dynamic
# values, unexpected fields, ...) is simply skipped: read-only, never
# rewritten, and never a reason to abort loading the rest of the file.


def _parse_window_rule_call(call_text: str, managed: bool) -> dict | None:
    """Turns one hl.window_rule({...}) call's source text into the same
    dict shape parse_rules_conf() produces, or None if it isn't one of the
    static shapes this app itself writes (workspace or float, matched on
    class or initial_title) — e.g. dynamic values, unsupported fields, or
    a table shaped differently than expected."""
    try:
        path, args = caelestia_core.parse_lua_call(call_text)
    except ValueError:
        return None
    if path != "hl.window_rule" or not args or not isinstance(args[0], dict):
        return None
    table = args[0]

    match_table = table.get("match")
    if not isinstance(match_table, dict):
        return None
    match_type = None
    match_val = None
    for candidate in ("class", "initial_title"):
        value = match_table.get(candidate)
        if isinstance(value, str):
            match_type, match_val = candidate, value
            break
    if match_type is None:
        return None

    workspace = table.get("workspace")
    float_val = table.get("float")
    if isinstance(workspace, str):
        rule = f"workspace {workspace}"
    elif isinstance(float_val, bool):
        rule = f"float {'true' if float_val else 'false'}"
    else:
        return None

    return {
        "rule":       rule,
        "match_type": match_type,
        "match_val":  match_val,
        "raw":        call_text.strip(),
        "managed":    managed,
    }


def _load_window_rules_lua() -> list[dict]:
    path = resolve_path("rules", Provider.LUA)
    if not path.exists():
        return []
    text = path.read_bytes().decode("utf-8")
    byte_range = managed_block_byte_range(path, WINDOW_RULES_LUA_BLOCK)

    result = []
    for start, _end, call_text in caelestia_core.find_lua_calls(text, "hl.window_rule"):
        managed = byte_range is not None and byte_range[0] <= start < byte_range[1]
        rule = _parse_window_rule_call(call_text, managed)
        if rule is not None:
            result.append(rule)
    return result


def _load_existing_rules() -> list[dict]:
    """Provider-aware replacement for calling parse_rules_conf() directly:
    routes to the Lua reader under Provider.LUA, otherwise unchanged."""
    provider = load_provider()
    if provider is None:
        return []
    if provider is Provider.LUA:
        return _load_window_rules_lua()
    return parse_rules_conf()


def _load_provider_page_state(provider: Provider | None) -> tuple[list[tuple[str, str]], dict, list[dict]]:
    if provider is None:
        return [], {}, []
    if provider is Provider.LUA:
        lua_workspaces = _load_workspaces_shared()
        workspace_options = (
            build_workspace_options(lua_workspaces) if lua_workspaces else _fallback_ws_options()
        )
    else:
        workspace_options = parse_monitors_conf()["workspace_options"]
    return workspace_options, load_window_rules_config(), _load_existing_rules()


def _merge_imported_rules(saved_rules: dict, existing_rules: list[dict]) -> set[str]:
    imported_keys = set()
    for entry in existing_rules:
        match_value = entry["match_val"]
        if not match_value:
            continue
        for wm_class in match_value.split("|"):
            wm_class = wm_class.strip().lstrip("^(").rstrip(")$")
            if not wm_class or wm_class in saved_rules:
                continue
            rule = entry["rule"].strip()
            workspace_rule = ""
            float_rule = "default"
            if rule.startswith("workspace "):
                workspace_rule = rule.split("workspace ", 1)[1].strip()
            elif rule.startswith("float "):
                float_rule = rule.split("float ", 1)[1].strip()
            if workspace_rule or float_rule != "default":
                saved_rules[wm_class] = {
                    "match_type": entry.get("match_type", "class"),
                    "workspace": workspace_rule or "default",
                    "float": float_rule,
                }
                imported_keys.add(wm_class)
    return imported_keys


def _build_window_rule_lua_tables(key: str, settings: dict) -> list[dict]:
    """Builds one or two hl.window_rule({...}) argument tables for a single
    wm_class/initial_title rule. Two calls (not one combined table) when
    both a workspace and a float behavior are set — mirroring how the
    .conf provider already emits two separate `windowrule = ...` lines for
    the same match in _generate_rules_lines, the lower-risk option that
    keeps parsing, UI roundtrip, and this app's existing data model
    unambiguous."""
    match_type = settings.get("match_type", "class")
    workspace = settings.get("workspace", "default")
    float_val = settings.get("float", "default")

    tables = []
    if workspace != "default":
        tables.append({"match": {match_type: key}, "workspace": workspace})
    if float_val != "default":
        tables.append({"match": {match_type: key}, "float": float_val == "true"})
    return tables


def _save_window_rules_lua(rules: dict) -> None:
    """Renders every rule as hl.window_rule({...}) call(s) and safely
    replaces the "window-rules" managed block in rules.lua. Raises
    LuaWriteError (propagated from write_managed_lua_block) if the
    generated file fails luac validation — the file on disk is then left
    unchanged. An empty `rules` dict produces a valid, empty block."""
    path = resolve_path("rules", Provider.LUA)
    lines = []
    for key, settings in rules.items():
        for table in _build_window_rule_lua_tables(key, settings):
            lines.append(caelestia_core.render_lua_call("hl.window_rule", [table]))
    write_managed_lua_block(path, WINDOW_RULES_LUA_BLOCK, lines)


def _save_window_rules_lua_and_reload(rules: dict) -> None:
    path = resolve_path("rules", Provider.LUA)
    lines = []
    for key, settings in rules.items():
        for table in _build_window_rule_lua_tables(key, settings):
            lines.append(caelestia_core.render_lua_call("hl.window_rule", [table]))
    write_managed_lua_block_and_reload(path, WINDOW_RULES_LUA_BLOCK, lines)


# ── Haupt-Seite ──────────────────────────────────────────────────────────────

class WindowRulesPage(Gtk.Box):
    def __init__(self, main_window, **kwargs):
        super().__init__(**kwargs)
        self.main_window = main_window
        self.set_orientation(Gtk.Orientation.VERTICAL)

        self._provider_banner = Adw.Banner()
        self._provider_banner.set_title(t("Choose a Hyprland configuration provider to unlock this page."))
        self.append(self._provider_banner)

        provider = load_provider()
        self._workspace_options, self.saved_rules, self._existing_rules = _load_provider_page_state(provider)
        self._imported_keys = _merge_imported_rules(self.saved_rules, self._existing_rules)
        self._rows: dict[str, "AppRuleRow"] = {}
        self._conflicts: list[str] = []
        self._scan_started = False
        self._provider_banner.set_revealed(provider is None)

        # Notebook mit zwei Tabs
        notebook = Gtk.Notebook()
        notebook.set_vexpand(True)
        self.append(notebook)
        notebook.append_page(self._build_app_tab(),      Gtk.Label(label=t("App rules")))
        notebook.append_page(self._build_existing_tab(), Gtk.Label(label=t("Existing rules")))

    # ── Tab 1 ─────────────────────────────────────────────────────────────────

    def _build_app_tab(self) -> Gtk.Widget:
        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)

        # Toolbar
        bar = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        bar.set_margin_top(12); bar.set_margin_bottom(8)
        bar.set_margin_start(12); bar.set_margin_end(12)
        self.search_entry = Gtk.SearchEntry()
        self.search_entry.set_hexpand(True)
        self.search_entry.set_placeholder_text(t("Search app..."))
        self.search_entry.connect("search-changed", self._on_search_changed)
        bar.append(self.search_entry)
        self._save_btn = Gtk.Button(label=t("Save & Apply"))
        self._save_btn.add_css_class("suggested-action")
        self._save_btn.connect("clicked", self._on_save_clicked)
        self._save_btn.set_sensitive(load_provider() is not None)
        bar.append(self._save_btn)
        box.append(bar)

        # Konflikt-Banner
        self.conflict_banner = Adw.Banner()
        self.conflict_banner.set_title(t("Conflicts detected"))
        self.conflict_banner.set_button_label(t("Details"))
        self.conflict_banner.connect("button-clicked", self._show_conflict_dialog)
        self.conflict_banner.set_revealed(False)
        box.append(self.conflict_banner)

        # Scroll + Liste
        scroller = Gtk.ScrolledWindow()
        scroller.set_vexpand(True)
        scroller.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        self.pref_group = Adw.PreferencesGroup()
        self.pref_group.set_margin_top(4); self.pref_group.set_margin_bottom(12)
        self.pref_group.set_margin_start(12); self.pref_group.set_margin_end(12)
        scroller.set_child(self.pref_group)
        box.append(scroller)

        self.spinner = Gtk.Spinner()
        self.spinner.set_halign(Gtk.Align.CENTER)
        self.spinner.set_size_request(-1, 48)
        box.append(self.spinner)
        if load_provider() is not None:
            self._start_app_scan()
        else:
            self.spinner.set_visible(False)
        return box

    def _start_app_scan(self):
        if self._scan_started:
            return
        self._scan_started = True
        self.spinner.set_visible(True)
        self.spinner.start()
        threading.Thread(
            target=lambda: GLib.idle_add(self._populate_list, _scan_desktop_files()),
            daemon=True,
        ).start()

    def _populate_list(self, apps: list[dict]):
        self.spinner.stop()
        self.spinner.set_visible(False)
        for app in apps:
            saved = self.saved_rules.get(app["wm_class"], {})
            row = AppRuleRow(app, saved, self._workspace_options, self._on_rule_changed)
            self._rows[app["name"]] = row
            self.pref_group.add(row)

    def _on_search_changed(self, entry):
        q = entry.get_text().lower()
        for name, row in self._rows.items():
            row.set_visible(q in name.lower())

    def _on_rule_changed(self):
        # Konflikterkennung: selbe wm_class → zwei verschiedene Workspaces
        rules = []
        for row in self._rows.values():
            wm, s = row.get_rule()
            ws = s.get("workspace", "default")
            rules.append((wm, ws))

        conflicts = [
            f"• {c.wm_class}: {c.first_workspace} ↔ {c.conflicting_workspace}"
            for c in caelestia_core.find_conflicts(rules)
        ]
        self._conflicts = conflicts
        if conflicts:
            self.conflict_banner.set_title(f"{len(conflicts)} {t('conflicts detected')}")
            self.conflict_banner.set_revealed(True)
        else:
            self.conflict_banner.set_revealed(False)

    def _show_conflict_dialog(self, *_):
        dialog = Adw.MessageDialog(heading="Konflikte", body="\n".join(self._conflicts) or "–")
        dialog.add_response("ok", "OK")
        dialog.set_transient_for(self.main_window)
        dialog.present()

    def _on_save_clicked(self, btn):
        if self._conflicts:
            self._show_conflict_dialog()
            return

        # Button während des Speicherns deaktivieren → verhindert Doppelklick
        btn.set_sensitive(False)
        btn.set_label(t("Saving..."))

        # Welche wm_classes haben bereits manuelle (nicht-managed) Regeln?
        manual_classes: set[str] = set()
        for entry in self._existing_rules:
            if not entry["managed"]:
                for cls in entry["match_val"].split("|"):
                    cls = cls.strip().lstrip("^(").rstrip(")$")
                    if cls:
                        manual_classes.add(cls)

        rules = {}
        for row in self._rows.values():
            key, settings = row.get_rule()
            ws     = settings.get("workspace", "default")
            float_ = settings.get("float",     "default")
            if ws == "default" and float_ == "default":
                continue
            # Klassen mit manueller Regel nur schreiben wenn User sie geändert hat
            if key in manual_classes and not row.is_user_modified():
                continue
            rules[key] = settings

        # Providerabhängig in die echte Hyprland-Konfiguration schreiben und
        # live anwenden, BEVOR der lokale JSON-Cache aktualisiert wird — so
        # kann der Cache nie einen Stand enthalten, der beim sicheren
        # Config-Schreiben (Lua: luac-Validierung) oder beim Reload
        # tatsächlich verworfen wurde.
        provider = load_provider()
        if provider is None:
            self.main_window.add_toast(
                Adw.Toast.new(t("Choose a Hyprland configuration provider first."))
            )
            btn.set_sensitive(True)
            btn.set_label(t("Save & Apply"))
            return
        try:
            if provider is Provider.LUA:
                _save_window_rules_lua_and_reload(rules)
            else:
                _write_rules_conf(_generate_rules_lines(rules))
        except Exception as e:
            self.main_window.add_toast(Adw.Toast.new(f"{t('Error:')} {e}"))
            btn.set_sensitive(True)
            btn.set_label(t("Save & Apply"))
            return

        save_window_rules_config(rules)
        self.main_window.add_toast(Adw.Toast.new(t("Rules saved and Hyprland reloaded.")))
        self._existing_rules = _load_existing_rules()
        self._refresh_existing_tab()
        btn.set_sensitive(True)
        btn.set_label(t("Save & Apply"))

    # ── Tab 2 ─────────────────────────────────────────────────────────────────

    def _build_existing_tab(self) -> Gtk.Widget:
        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self._existing_desc_label = Gtk.Label()
        self._existing_desc_label.set_margin_top(10)
        self._existing_desc_label.set_margin_bottom(6)
        self._existing_desc_label.set_margin_start(12)
        self._existing_desc_label.set_halign(Gtk.Align.START)
        box.append(self._existing_desc_label)

        scroller = Gtk.ScrolledWindow()
        scroller.set_vexpand(True)
        scroller.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        self._existing_group = Adw.PreferencesGroup()
        self._existing_group.set_margin_top(4); self._existing_group.set_margin_bottom(12)
        self._existing_group.set_margin_start(12); self._existing_group.set_margin_end(12)
        scroller.set_child(self._existing_group)
        box.append(scroller)
        self._refresh_existing_tab()
        return box

    def _refresh_existing_tab(self):
        provider = load_provider()
        if provider is None:
            rules_path = ""
            desc = t("Choose Yes or No in the provider dialog before reading configuration.")
        else:
            rules_path = resolve_path("rules", provider)
            desc = (
                t("All hl.window_rule(...) entries from {path}  –  🔒 manual  /  ⚙ managed by this app")
                if provider is Provider.LUA
                else t("All windowrule entries from {path}  –  🔒 manual  /  ⚙ managed by this app")
            ).format(path=rules_path)
        self._existing_desc_label.set_markup(f"<small>{GLib.markup_escape_text(desc)}</small>")

        # AdwPreferencesGroup erlaubt kein remove() auf seine Rows —
        # stattdessen die Group komplett ersetzen.
        parent = self._existing_group.get_parent()   # ScrolledWindow
        new_group = Adw.PreferencesGroup()
        new_group.set_margin_top(4); new_group.set_margin_bottom(12)
        new_group.set_margin_start(12); new_group.set_margin_end(12)

        if not self._existing_rules:
            new_group.add(Adw.ActionRow(
                title=(
                    t("Hyprland configuration provider required")
                    if provider is None
                    else t("No windowrule entries found.")
                ),
                subtitle=(
                    t("Choose Yes or No in the provider dialog before editing configuration.")
                    if provider is None
                    else str(rules_path)
                ),
            ))
        else:
            for entry in self._existing_rules:
                icon = "⚙" if entry["managed"] else "🔒"
                row  = Adw.ActionRow()
                row.set_title(f"{icon}  {entry['rule']}")
                row.set_subtitle(
                    f"match:{entry['match_type']} {entry['match_val']}"
                    if entry["match_type"] else entry["raw"]
                )
                new_group.add(row)

        if parent:
            parent.set_child(new_group)
        self._existing_group = new_group

    def on_provider_changed(self):
        provider = load_provider()
        self._provider_banner.set_revealed(provider is None)
        self._save_btn.set_sensitive(provider is not None)
        if provider is None:
            return
        self._workspace_options, self.saved_rules, self._existing_rules = _load_provider_page_state(provider)
        self._imported_keys = _merge_imported_rules(self.saved_rules, self._existing_rules)
        self._refresh_existing_tab()
        self._start_app_scan()


# ── Einzelne App-Zeile ────────────────────────────────────────────────────────

class AppRuleRow(Adw.ActionRow):
    def __init__(self, app_info: dict, saved_settings: dict,
                 workspace_options: list[tuple[str, str]], on_change_cb):
        super().__init__()
        self._wm_class    = app_info["wm_class"]
        self._is_web_app  = app_info.get("is_web_app", False)
        self._cb          = on_change_cb


        self.set_title(app_info["name"])
        sub = app_info["wm_class"] or t("Unknown class")
        if self._is_web_app: sub += "  •  Web app"
        self.set_subtitle(sub)

        # Icon
        icon = Gtk.Image(); icon.set_pixel_size(32)
        icon_name = app_info.get("icon", "")
        theme = Gtk.IconTheme.get_for_display(icon.get_display()) if icon.get_display() else None
        if theme and icon_name and theme.has_icon(icon_name):
            icon.set_from_icon_name(icon_name)
        else:
            icon.set_from_icon_name("application-x-executable")
        icon.set_margin_end(8)
        self.add_prefix(icon)

        def _make_suffix(label_text, combo_options, saved_key, default_val):
            vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
            vbox.set_valign(Gtk.Align.CENTER)
            lbl = Gtk.Label(label=label_text)
            lbl.add_css_class("caption"); lbl.set_halign(Gtk.Align.START)
            vbox.append(lbl)
            combo = Gtk.ComboBoxText()
            for opt_id, opt_lbl in combo_options:
                combo.append(opt_id, opt_lbl)
            combo.set_active_id(saved_settings.get(saved_key, default_val))
            combo.connect("changed", lambda _: self._cb())
            vbox.append(combo)
            self.add_suffix(vbox)
            return combo

        default_match = "initial_title" if self._is_web_app else "class"
        self.match_combo = _make_suffix("Match",     MATCH_TYPE_OPTIONS, "match_type", default_match)
        self.ws_combo    = _make_suffix("Workspace", workspace_options,  "workspace",  "default")
        self.float_combo = _make_suffix(t("Behavior"), FLOAT_OPTIONS,      "float",      "default")

        # Ausgangszustand merken — zum Vergleich beim Speichern
        self._initial_state = {
            "match_type": self.match_combo.get_active_id() or "class",
            "workspace":  self.ws_combo.get_active_id()    or "default",
            "float":      self.float_combo.get_active_id() or "default",
        }

    def is_user_modified(self) -> bool:
        """True wenn der User mindestens einen Wert geändert hat."""
        current = {
            "match_type": self.match_combo.get_active_id() or "class",
            "workspace":  self.ws_combo.get_active_id()    or "default",
            "float":      self.float_combo.get_active_id() or "default",
        }
        return current != self._initial_state

    def get_rule(self) -> tuple[str, dict]:
        return self._wm_class, {
            "match_type": self.match_combo.get_active_id() or "class",
            "workspace":  self.ws_combo.get_active_id()    or "default",
            "float":      self.float_combo.get_active_id() or "default",
        }
