import subprocess
import caelestia_core
from src.lang import t
from gi.repository import Gtk, Adw, GLib
from src.config import HYPR_MONITORS_CONF, parse_monitors_conf
from src.hypr_provider import (
    Provider,
    load_provider,
    read_managed_lua_block,
    resolve_path,
    write_managed_legacy_block,
    write_managed_lua_block,
    write_managed_lua_block_and_reload,
)

MANAGED_MARKER = "# Workspaces – Auto-generated by Caelestia Settings"
WORKSPACES_CONF_BLOCK = "workspaces"
WORKSPACES_LUA_BLOCK = "workspaces"


# ── Parser & Writer ───────────────────────────────────────────────────────────

def _load_workspaces() -> list[dict]:
    """
    Gibt alle Workspace-Regeln zurück, providerabhängig aus monitors.conf
    (workspace-Zeilen) oder monitors.lua (hl.workspace_rule(...)-Block):
    [ {"number": 1, "monitor": "DP-1", "default": True, "persistent": False} ]
    """
    if load_provider() is Provider.LUA:
        return _load_workspaces_lua()
    return _load_workspaces_conf()


def _load_workspaces_lua() -> list[dict]:
    path = resolve_path("monitors", Provider.LUA)
    result = []
    for line in read_managed_lua_block(path, WORKSPACES_LUA_BLOCK):
        line = line.strip()
        if not line.startswith("hl.workspace_rule("):
            continue
        try:
            _, args = caelestia_core.parse_lua_call(line)
        except ValueError:
            continue
        if not args or not isinstance(args[0], dict):
            continue
        table = args[0]
        try:
            num = int(table.get("workspace", ""))
        except (TypeError, ValueError):
            continue
        result.append({
            "number":     num,
            "monitor":    table.get("monitor", ""),
            "default":    bool(table.get("default", False)),
            "persistent": bool(table.get("persistent", False)),
        })
    return sorted(result, key=lambda w: w["number"])


def _build_workspace_lua_table(ws: dict) -> dict:
    table = {"workspace": str(ws["number"])}
    if ws["monitor"]:
        table["monitor"] = ws["monitor"]
    if ws["default"]:
        table["default"] = True
    if ws["persistent"]:
        table["persistent"] = True
    return table


def _save_workspaces_lua(workspaces: list[dict]) -> None:
    """Renders every workspace rule as hl.workspace_rule({...}) and safely
    replaces the "workspaces" managed block in monitors.lua. Raises
    LuaWriteError if the result fails luac validation — file left
    unchanged in that case."""
    path = resolve_path("monitors", Provider.LUA)
    lines = [
        caelestia_core.render_lua_call("hl.workspace_rule", [_build_workspace_lua_table(ws)])
        for ws in sorted(workspaces, key=lambda w: w["number"])
    ]
    write_managed_lua_block(path, WORKSPACES_LUA_BLOCK, lines)


def _save_workspaces_lua_and_reload(workspaces: list[dict]) -> None:
    path = resolve_path("monitors", Provider.LUA)
    lines = [
        caelestia_core.render_lua_call("hl.workspace_rule", [_build_workspace_lua_table(ws)])
        for ws in sorted(workspaces, key=lambda w: w["number"])
    ]
    write_managed_lua_block_and_reload(path, WORKSPACES_LUA_BLOCK, lines)


def _load_workspaces_conf() -> list[dict]:
    """
    Gibt alle workspace-Zeilen aus monitors.conf zurück:
    [ {"number": 1, "monitor": "DP-1", "default": True, "persistent": False} ]
    """
    result = []
    if not HYPR_MONITORS_CONF.exists():
        return result
    try:
        for line in HYPR_MONITORS_CONF.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if not line.startswith("workspace"):
                continue
            rest   = line.split("=", 1)[1]
            tokens = [t.strip() for t in rest.split(",")]
            if not tokens:
                continue
            try:
                num = int(tokens[0])
            except ValueError:
                continue
            monitor    = ""
            is_default = False
            persistent = False
            for tok in tokens[1:]:
                if tok.startswith("monitor:"):
                    monitor = tok.split("monitor:")[1]
                if "default:true" in tok:
                    is_default = True
                if "persistent:true" in tok:
                    persistent = True
            result.append({
                "number":     num,
                "monitor":    monitor,
                "default":    is_default,
                "persistent": persistent,
            })
    except Exception as e:
        print(f"Workspace laden fehler: {e}")
    return sorted(result, key=lambda w: w["number"])


def _get_monitor_names() -> list[str]:
    try:
        import json
        res = subprocess.run(
            ["hyprctl", "monitors", "-j"],
            capture_output=True, text=True, check=True, timeout=3
        )
        return [m["name"] for m in json.loads(res.stdout)]
    except Exception:
        if load_provider() is Provider.LUA:
            return _get_monitor_names_lua_fallback()
        data = parse_monitors_conf()
        return [m["name"] for m in data.get("monitors", [])]


def _get_monitor_names_lua_fallback() -> list[str]:
    """Used only when hyprctl itself is unreachable: reads monitor names
    back out of the app's own managed hl.monitor(...) block, since
    monitors.lua may not exist or may not be require()'d yet either."""
    path = resolve_path("monitors", Provider.LUA)
    names = []
    for line in read_managed_lua_block(path, "monitors"):
        line = line.strip()
        if not line.startswith("hl.monitor("):
            continue
        try:
            _, args = caelestia_core.parse_lua_call(line)
        except ValueError:
            continue
        if args and isinstance(args[0], dict) and args[0].get("output"):
            names.append(args[0]["output"])
    return names


def _build_workspace_line(ws: dict) -> str:
    parts = [str(ws["number"])]
    if ws["monitor"]:
        parts.append(f"monitor:{ws['monitor']}")
    if ws["default"]:
        parts.append("default:true")
    if ws["persistent"]:
        parts.append("persistent:true")
    return f"workspace = {', '.join(parts)}"


def _save_workspaces(workspaces: list[dict]):
    """Schreibt Workspace-Regeln providerabhängig und wendet sie live an.

    Unter Lua kann der transaktionale Writer LuaWriteError (ungültiges
    generiertes Lua) oder RuntimeError (hyprctl-Fehler) werfen —
    beide werden absichtlich nicht hier gefangen, sondern von _on_save
    aufgefangen und als Toast angezeigt.
    """
    provider = load_provider()
    if provider is None:
        raise RuntimeError(t("Choose a Hyprland configuration provider first."))
    if provider is Provider.LUA:
        _save_workspaces_lua_and_reload(workspaces)
        return
    _save_workspaces_conf(workspaces)


def _save_workspaces_conf(workspaces: list[dict]):
    """Replace only the app-owned workspace block in monitors.conf."""
    if not HYPR_MONITORS_CONF.exists():
        return
    lines = [_build_workspace_line(ws) for ws in sorted(workspaces, key=lambda w: w["number"])]
    write_managed_legacy_block(
        HYPR_MONITORS_CONF,
        WORKSPACES_CONF_BLOCK,
        lines,
        legacy_marker=MANAGED_MARKER,
        legacy_line_predicate=lambda line: not line.strip() or line.strip().startswith("workspace ="),
    )

    # Live anwenden
    for ws in workspaces:
        keyword = _build_workspace_line(ws).split("=", 1)[1].strip()
        try:
            subprocess.run(
                ["hyprctl", "keyword", "workspace", keyword],
                capture_output=True, timeout=3
            )
        except Exception as e:
            print(f"hyprctl workspace fehler: {e}")


# ── Haupt-Seite ───────────────────────────────────────────────────────────────

class WorkspacesPage(Gtk.Box):
    def __init__(self, main_window, **kwargs):
        super().__init__(**kwargs)
        self.main_window = main_window
        self.set_orientation(Gtk.Orientation.VERTICAL)
        self.set_spacing(0)

        self._workspaces: list[dict] = []
        self._monitor_names: list[str] = []
        self._rows: list["WorkspaceRow"] = []

        # ── Toolbar ──────────────────────────────────────────────────────
        bar = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        bar.set_margin_top(12)
        bar.set_margin_bottom(8)
        bar.set_margin_start(12)
        bar.set_margin_end(12)

        title = Gtk.Label(label=t("Workspaces"))
        title.add_css_class("heading")
        title.set_hexpand(True)
        title.set_halign(Gtk.Align.START)
        bar.append(title)

        add_btn = Gtk.Button(label=t("+ Add"))
        add_btn.connect("clicked", self._on_add)
        bar.append(add_btn)

        save_btn = Gtk.Button(label=t("Save & Apply"))
        save_btn.add_css_class("suggested-action")
        save_btn.connect("clicked", self._on_save)
        bar.append(save_btn)

        reload_btn = Gtk.Button()
        reload_btn.set_icon_name("view-refresh-symbolic")
        reload_btn.set_tooltip_text(t("Reload"))
        reload_btn.connect("clicked", lambda _: self._load())
        bar.append(reload_btn)

        self.append(bar)

        # ── Monitor-Gruppen ───────────────────────────────────────────────
        scroller = Gtk.ScrolledWindow()
        scroller.set_vexpand(True)
        scroller.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        self.append(scroller)

        self._content = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=12)
        self._content.set_margin_top(4)
        self._content.set_margin_bottom(12)
        self._content.set_margin_start(12)
        self._content.set_margin_end(12)
        scroller.set_child(self._content)

        self._load()

    # ── Laden ─────────────────────────────────────────────────────────────

    def _load(self):
        # Content leeren
        while child := self._content.get_first_child():
            self._content.remove(child)
        self._rows.clear()

        self._monitor_names = _get_monitor_names()
        self._workspaces    = _load_workspaces()

        if not self._workspaces:
            status = Adw.StatusPage()
            status.set_icon_name("preferences-desktop-display-symbolic")
            status.set_title(t("No workspaces found"))
            status.set_description(t("Add a workspace or check your monitors.conf"))
            self._content.append(status)
            return

        # Gruppiert nach Monitor
        by_monitor: dict[str, list[dict]] = {}
        for ws in self._workspaces:
            mon = ws["monitor"] or "Ohne Monitor"
            by_monitor.setdefault(mon, []).append(ws)

        # Reihenfolge: wie in hyprctl monitors (physische Reihenfolge), Rest danach
        order = [m for m in self._monitor_names if m in by_monitor]
        for m in by_monitor:
            if m not in order:
                order.append(m)
        # Innerhalb jeder Gruppe nach WS-Nummer sortieren
        for mon in by_monitor:
            by_monitor[mon].sort(key=lambda w: w["number"])

        for mon in order:
            wss = by_monitor[mon]
            group = Adw.PreferencesGroup(title=f"Monitor: {mon}")
            for ws in wss:
                row = WorkspaceRow(ws, self._monitor_names, self._on_delete)
                self._rows.append(row)
                group.add(row)
            self._content.append(group)

    # ── Aktionen ──────────────────────────────────────────────────────────

    def _on_add(self, _btn):
        # Nächste freie Workspace-Nummer finden
        used = {r.get_data()["number"] for r in self._rows}
        num  = next((i for i in range(1, 100) if i not in used), 1)
        default_mon = self._monitor_names[0] if self._monitor_names else ""

        new_ws = {"number": num, "monitor": default_mon, "default": False, "persistent": False}

        # Zur passenden Gruppe hinzufügen oder neue erstellen
        group = None
        child = self._content.get_first_child()
        while child:
            if isinstance(child, Adw.PreferencesGroup):
                if child.get_title() == f"Monitor: {default_mon}":
                    group = child
                    break
            child = child.get_next_sibling()

        if group is None:
            group = Adw.PreferencesGroup(title=f"Monitor: {default_mon}")
            self._content.append(group)

        row = WorkspaceRow(new_ws, self._monitor_names, self._on_delete)
        self._rows.append(row)
        group.add(row)

    def _on_delete(self, row: "WorkspaceRow"):
        self._rows.remove(row)
        # Row aus PreferencesGroup entfernen — neu laden ist einfacher
        try:
            self._save_and_reload()
        except Exception as e:
            self.main_window.add_toast(Adw.Toast.new(f"Fehler: {e}"))

    def _on_save(self, btn):
        btn.set_sensitive(False)
        btn.set_label(t("Saving..."))
        try:
            self._save_and_reload()
            self.main_window.add_toast(
                Adw.Toast.new(t("Workspaces saved and applied."))
            )
        except Exception as e:
            self.main_window.add_toast(Adw.Toast.new(f"Fehler: {e}"))
        finally:
            btn.set_sensitive(True)
            btn.set_label(t("Save & Apply"))

    def _save_and_reload(self):
        data = [r.get_data() for r in self._rows]
        _save_workspaces(data)
        GLib.timeout_add(400, self._load)


# ── Einzelne Workspace-Zeile ──────────────────────────────────────────────────

class WorkspaceRow(Adw.ActionRow):
    def __init__(self, ws: dict, monitor_names: list[str], on_delete_cb):
        super().__init__()
        self._ws         = ws.copy()
        self._delete_cb  = on_delete_cb
        self._loading    = True

        self.set_title(f"Workspace {ws['number']}")

        # ── Nummer ──
        num_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
        num_box.set_valign(Gtk.Align.CENTER)
        num_lbl = Gtk.Label(label=t("No."))
        num_lbl.add_css_class("caption")
        num_box.append(num_lbl)
        self._num_spin = Gtk.SpinButton.new_with_range(1, 99, 1)
        self._num_spin.set_value(ws["number"])
        self._num_spin.set_size_request(64, -1)
        self._num_spin.connect("value-changed", self._on_changed)
        num_box.append(self._num_spin)
        self.add_suffix(num_box)

        # ── Monitor ──
        mon_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
        mon_box.set_valign(Gtk.Align.CENTER)
        mon_lbl = Gtk.Label(label=t("Monitor"))
        mon_lbl.add_css_class("caption")
        mon_box.append(mon_lbl)
        self._mon_combo = Gtk.ComboBoxText()
        for name in monitor_names:
            self._mon_combo.append(name, name)
        if ws["monitor"]:
            self._mon_combo.set_active_id(ws["monitor"])
        else:
            self._mon_combo.set_active(0)
        self._mon_combo.connect("changed", self._on_changed)
        mon_box.append(self._mon_combo)
        self.add_suffix(mon_box)

        # ── Default ──
        def_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
        def_box.set_valign(Gtk.Align.CENTER)
        def_lbl = Gtk.Label(label=t("Default ★"))
        def_lbl.add_css_class("caption")
        def_box.append(def_lbl)
        self._default_check = Gtk.CheckButton()
        self._default_check.set_active(ws["default"])
        self._default_check.set_halign(Gtk.Align.CENTER)
        self._default_check.connect("toggled", self._on_changed)
        def_box.append(self._default_check)
        self.add_suffix(def_box)

        # ── Persistent ──
        per_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
        per_box.set_valign(Gtk.Align.CENTER)
        per_lbl = Gtk.Label(label=t("Always visible"))
        per_lbl.add_css_class("caption")
        per_box.append(per_lbl)
        self._persist_check = Gtk.CheckButton()
        self._persist_check.set_active(ws["persistent"])
        self._persist_check.set_halign(Gtk.Align.CENTER)
        self._persist_check.set_tooltip_text(t("Workspace stays visible even without windows"))
        self._persist_check.connect("toggled", self._on_changed)
        per_box.append(self._persist_check)
        self.add_suffix(per_box)

        # ── Löschen ──
        del_btn = Gtk.Button()
        del_btn.set_icon_name("user-trash-symbolic")
        del_btn.add_css_class("destructive-action")
        del_btn.set_valign(Gtk.Align.CENTER)
        del_btn.connect("clicked", lambda _: self._delete_cb(self))
        self.add_suffix(del_btn)

        self._loading = False

    def _on_changed(self, *_):
        if self._loading:
            return
        num = int(self._num_spin.get_value())
        self.set_title(f"Workspace {num}")
        self._ws = self.get_data()

    def get_data(self) -> dict:
        return {
            "number":     int(self._num_spin.get_value()),
            "monitor":    self._mon_combo.get_active_id() or "",
            "default":    self._default_check.get_active(),
            "persistent": self._persist_check.get_active(),
        }
