//! Parsing of Hyprland rules.conf into window rules.
//!
//! Pure string-in / data-out functions: no file I/O here, so everything
//! is unit-testable without touching the filesystem. Thin I/O wrappers
//! come later, together with the PyO3 bindings.

/// A single `windowrule = ...` entry extracted from rules.conf.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WindowRule {
    pub rule: String,
    pub match_type: String,
    pub match_val: String,
    pub raw: String,
    pub managed: bool,
}

/// Marks the start of the block this app owns; every rule on or after this
/// line is `managed = true` so the UI knows it is allowed to rewrite it.
/// The marker line itself is skipped, not emitted as a rule.
const LEGACY_MANAGED_MARKER: &str = "# Auto-generated by Caelestia Settings – Fenster-Regeln";
const MANAGED_BEGIN_MARKER: &str = "# BEGIN Caelestia Settings managed block: window-rules";
const MANAGED_END_MARKER: &str = "# END Caelestia Settings managed block: window-rules";

/// Parses all `windowrule = ...` lines from rules.conf content.
pub fn parse_rules_conf(input: &str) -> Vec<WindowRule> {
    let mut result = Vec::new();
    let mut in_managed = false;

    for raw_line in input.lines() {
        let line = raw_line.trim();

        if line == LEGACY_MANAGED_MARKER || line == MANAGED_BEGIN_MARKER {
            in_managed = true;
            continue;
        }
        if line == MANAGED_END_MARKER {
            in_managed = false;
            continue;
        }
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if !line.starts_with("windowrule") {
            continue;
        }

        // A windowrule line with no "=" has nothing to extract. The Python
        // original's bare try/except would abort parsing the *entire* file
        // at this point (dropping every rule after it); that is a bug, not
        // a behavior worth preserving, so we just skip the malformed line.
        let Some((_, rest)) = line.split_once('=') else {
            continue;
        };
        let rest = rest.trim();

        // rsplit on the *last* ", match:" mirrors the Python original
        // (`rest.rsplit(", match:", 1)`), in case the value itself
        // contains the literal substring earlier on.
        let (rule_part, match_type, match_val) = match rest.rfind(", match:") {
            Some(idx) => {
                let rule_part = &rest[..idx];
                let match_part = rest[idx + ", match:".len()..].trim();

                // split(None, 1) in Python: first whitespace *run* is the
                // separator, and an empty match_part yields no tokens at
                // all (rather than one empty token) — hence match_type
                // defaults to "class" when no first token exists.
                let mut tokens = match_part.splitn(2, char::is_whitespace);
                let match_type = tokens.next().filter(|s| !s.is_empty()).unwrap_or("class");
                let match_val = tokens.next().unwrap_or("").trim_start();
                (rule_part, match_type, match_val)
            }
            None => (rest, "", ""),
        };

        result.push(WindowRule {
            rule: rule_part.trim().to_string(),
            match_type: match_type.to_string(),
            match_val: match_val.to_string(),
            raw: line.to_string(),
            managed: in_managed,
        });
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_rule_without_match() {
        let rules = parse_rules_conf("windowrule = float, class:^(kitty)$");
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0].rule, "float, class:^(kitty)$");
        assert_eq!(rules[0].match_type, "");
        assert_eq!(rules[0].match_val, "");
        assert!(!rules[0].managed);
    }

    #[test]
    fn parses_rule_with_match() {
        let rules =
            parse_rules_conf("windowrule = workspace special:music, match: class feishin|Spotify");
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0].rule, "workspace special:music");
        assert_eq!(rules[0].match_type, "class");
        assert_eq!(rules[0].match_val, "feishin|Spotify");
    }

    #[test]
    fn splits_match_on_last_occurrence_only() {
        let rules = parse_rules_conf("windowrule = float, match: literally, match: class Spotify");
        assert_eq!(rules[0].rule, "float, match: literally");
        assert_eq!(rules[0].match_type, "class");
        assert_eq!(rules[0].match_val, "Spotify");
    }

    #[test]
    fn empty_match_part_defaults_type_to_class() {
        let rules = parse_rules_conf("windowrule = float, match:   ");
        assert_eq!(rules[0].match_type, "class");
        assert_eq!(rules[0].match_val, "");
    }

    #[test]
    fn extra_whitespace_between_match_tokens_is_trimmed() {
        let rules = parse_rules_conf("windowrule = float, match:    class     Spotify");
        assert_eq!(rules[0].match_type, "class");
        assert_eq!(rules[0].match_val, "Spotify");
    }

    #[test]
    fn marker_line_toggles_managed_but_is_not_a_rule() {
        let input = "\
windowrule = float, class:^(before)$
# Auto-generated by Caelestia Settings – Fenster-Regeln
windowrule = float, class:^(after)$
";
        let rules = parse_rules_conf(input);
        assert_eq!(rules.len(), 2);
        assert!(!rules[0].managed);
        assert!(rules[1].managed);
    }

    #[test]
    fn begin_and_end_markers_toggle_managed_false_true_false() {
        let input = "\
windowrule = float true, match: class before
# BEGIN Caelestia Settings managed block: window-rules
windowrule = float true, match: class managed
# END Caelestia Settings managed block: window-rules
windowrule = float true, match: class after
";
        let rules = parse_rules_conf(input);
        assert_eq!(rules.len(), 3);
        assert_eq!(
            rules.iter().map(|rule| rule.managed).collect::<Vec<_>>(),
            [false, true, false]
        );
    }

    #[test]
    fn skips_blank_lines_comments_and_non_windowrule_lines() {
        let input = "\n# just a comment
bind = SUPER, T, exec, kitty
windowrule = float, class:^(kitty)$
";
        let rules = parse_rules_conf(input);
        assert_eq!(rules.len(), 1);
    }

    #[test]
    fn raw_preserves_trimmed_original_line() {
        let rules = parse_rules_conf("   windowrule = float, class:^(kitty)$   ");
        assert_eq!(rules[0].raw, "windowrule = float, class:^(kitty)$");
    }

    #[test]
    fn skips_malformed_line_without_equals_sign() {
        let input = "\
windowrule float, class:^(kitty)$
windowrule = float, class:^(after)$
";
        let rules = parse_rules_conf(input);
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0].rule, "float, class:^(after)$");
    }
}
