import subprocess
import json
from gi.repository import Gtk, Adw, GLib
from src.config import save_monitor_config, HYPR_MONITORS_CONF
from src.pages.general import GeneralPage
from src.pages.monitor import MonitorPage, MonitorWidget
from src.pages.audio import AudioPage
from src.pages.updates import UpdatePage
from src.pages.about import AboutPage

class MainWindow(Adw.ApplicationWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_title("Caelestia Einstellungen")
        self.set_default_size(800, 600)

        root = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.set_content(root)
        
        header = Adw.HeaderBar()
        root.append(header)
        
        self.apply_btn = Gtk.Button(label="Anwenden")
        self.apply_btn.add_css_class("suggested-action")
        self.apply_btn.set_visible(False)
        self.apply_btn.connect("clicked", self.on_apply)
        header.pack_end(self.apply_btn)

        main_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        main_box.set_vexpand(True)
        root.append(main_box)

        self.stack = Gtk.Stack()
        self.stack.set_vexpand(True)
        self.stack.set_hexpand(True)
        
        sidebar = Gtk.StackSidebar()
        sidebar.set_stack(self.stack)
        
        main_box.append(sidebar)
        main_box.append(self.stack)

        # Seiten laden
        self.mon_page = MonitorPage(self)
        self.stack.add_titled(GeneralPage(self), "gen", "Allgemein")
        self.stack.add_titled(self.mon_page, "mon", "Monitor")
        self.stack.add_titled(AudioPage(self), "audio", "Audio")
        self.stack.add_titled(UpdatePage(self), "upd", "Updates")
        self.stack.add_titled(AboutPage(self), "about", "Über")

        self.stack.connect("notify::visible-child", self.on_page_change)

    def on_page_change(self, stack, _):
        self.apply_btn.set_visible(stack.get_visible_child() == self.mon_page)

    def on_apply(self, btn):
        if self.stack.get_visible_child() != self.mon_page: return
        print("Wende Monitor-Einstellungen an...")
        
        new_conf = self.mon_page.get_all_widget_settings()
        save_monitor_config(new_conf)
        
        cmds, lines = self.gen_hypr_cmds(new_conf)
        self.save_hypr_conf(lines)
        
        for c in cmds:
            try: subprocess.run(c, check=True, timeout=2)
            except Exception as e: print(f"Fehler cmd: {e}")
            
        GLib.timeout_add(500, self.mon_page.load_monitors)

    def save_hypr_conf(self, lines):
        try:
            HYPR_MONITORS_CONF.parent.mkdir(parents=True, exist_ok=True)
            with open(HYPR_MONITORS_CONF, 'w') as f:
                f.write("# Auto-generated by Caelestia Settings\n")
                f.write("\n".join(lines))
        except Exception as e: print(f"Fehler Config Save: {e}")

    def gen_hypr_cmds(self, conf):
        cmds = []
        lines = []
        try:
            res = subprocess.run(['hyprctl', 'monitors', '-j'], capture_output=True, text=True, check=True)
            live = {m['name']: m for m in json.loads(res.stdout)}
            
            for name, sett in conf.items():
                res_val = sett.get("resolution", "preferred").replace("Hz", "")
                arr = sett.get("arrange", "auto")
                tgt = sett.get("target")
                
                parts = [name]
                
                if arr == "deaktivieren": parts.append("disable")
                elif arr == "spiegeln":
                    if tgt in live: parts.append(f"mirror,{tgt}")
                    else: continue
                elif arr == "auto":
                    parts.extend([res_val, "auto", "1"])
                elif arr == "current_pos":
                    # Behalte aktuelle Position aus Live-Daten
                    if name in live:
                        cur = live[name]
                        parts.extend([res_val, f"{cur['x']}x{cur['y']}", "1"])
                    else: parts.extend([res_val, "auto", "1"])
                elif arr in ["rechts", "links", "darueber", "darunter"]:
                    if tgt in live:
                        t = live[tgt]
                        # Parse eigene Breite aus gewähltem Res-String
                        try:
                            w_str, h_str = res_val.split('@')[0].split('x')
                            my_w, my_h = int(w_str), int(h_str)
                        except: my_w, my_h = 1920, 1080 # Fallback
                        
                        nx, ny = 0, 0
                        if arr == "rechts": nx, ny = t['x'] + t['width'], t['y']
                        elif arr == "links": nx, ny = t['x'] - my_w, t['y']
                        elif arr == "darunter": nx, ny = t['x'], t['y'] + t['height']
                        elif arr == "darueber": nx, ny = t['x'], t['y'] - my_h
                        
                        parts.extend([res_val, f"{nx}x{ny}", "1"])
                    else: continue
                else: parts.extend([res_val, "auto", "1"])
                
                final = ",".join(parts)
                cmds.append(["hyprctl", "keyword", "monitor", final])
                lines.append(f"monitor = {final}")
                
        except Exception as e: print(f"Fehler Gen Cmds: {e}")
        return cmds, lines